package com.designprototype.workshop.data

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.put
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * [DwMarketAnalysis] and [DwCostIntegrity] against the Python they are ports of, BY VALUE.
 *
 * WHY THIS SHAPE AND NOT A LIST OF ASSERTIONS. A port is not proven by testing its properties — every
 * property this pair has is one both implementations could plausibly get wrong in the same shape and
 * differently in the last digit, which is exactly where money lives. So there is one case table
 * (`dw-analysis-cases.json`), it is fed to `backend/app/services/{market_analysis,cost_integrity}.py`
 * verbatim, and the payload Python produced for every case is frozen into `dw-analysis-expected.json`.
 * This test recomputes all 59 cases here and DIFFS the two documents leaf by leaf. When it fails it
 * names the case, the JSON path, and both values, because "the Kotlin is wrong somewhere" is not a
 * finding anybody can act on.
 *
 * THE TABLE IS ITSELF TESTED, by breaking each guard in turn and checking that a case notices. Every
 * guard below is one an idiomatic port would not have written, so a table that still passed without it
 * would be measuring nothing: HALF_EVEN→HALF_UP moves 5 leaves, dropping `\p{M}` moves 4, replacing
 * `asNumber`'s grammar gate with `toDoubleOrNull` moves 16, UTF-16 string order moves 2, natural
 * `Double` ordering moves 12, a `<` tolerance moves 3, and `DwPy.strip`→`trim()` moves 31. That last
 * one moved NOTHING until `m28-python-whitespace-forms` was added — the table held a no-break space,
 * which Kotlin's `trim()` already strips, and no U+0085, which is the one character the guard exists
 * for. A guard nothing can break is a guard nobody can trust.
 *
 * THE GOLDEN IS A CACHE OF THE PYTHON, NOT A SECOND OPINION. It is regenerated by running the case
 * table through the backend modules; if the two ever disagree, the Python is right and this side is
 * broken. Freezing it is what lets the comparison keep running on a build machine with no Python and
 * no backend checkout — which is every machine this module is built on.
 *
 * THE CASES ARE CHOSEN FOR WHERE THE TWO LANGUAGES PART COMPANY, not for coverage of the happy path:
 *
 *  * `m25` — a mean of 531.125 and a median of 624.5. Python rounds half to EVEN and Java's
 *    `Formatter` rounds half AWAY, so a naive port prints 531.13 and ₹625 against the server's
 *    531.12 and ₹624, in the same figure, in two copies of one report.
 *  * `c01` — a competitor at the 37.5th percentile, whose sentence therefore says "below what 62% of
 *    buyers said they would pay". Half away from zero makes that 63%.
 *  * `m20` — an Odia SWOT point against an Odia response. A tokeniser without `\p{M}` shatters ରଙ୍ଗ
 *    and ଦାମ at their virama and matra, the fragments fall under the three-character floor, and the
 *    point is reported as an unevidenced assertion.
 *  * `m22` — two respondents with equal overlap, one named with an astral character and one with a
 *    private-use character. UTF-16 order and code-point order disagree about which comes first.
 *  * `m10` — a sample holding both 0.0 and -0.0. Kotlin's natural ordering separates them; Python's
 *    `<` does not, so a stable sort leaves them as collected and the maximum is -0.0.
 *  * `m08`/`m09` — "0x1A", "1.5f", "NaN", "1__0" (all of which `Double.parseDouble` or
 *    `float()` disagree about), "1_000", "1,25,000" and Odia/Arabic-Indic digits.
 *  * `k07`/`k08` — a discrepancy of exactly ₹1.00 and one of ₹1.01, either side of the tolerance.
 *  * `k17` — a margin of exactly 25.25%, which prints 25.2 half-to-even and 25.3 half-away.
 *  * `m28` — U+0085 and the narrow and figure no-break spaces around a price, a respondent name, a
 *    product tag and a SWOT evidence field. `str.strip()` removes all of them; `trim()` misses U+0085.
 *
 * TWO CASES ARE NOT CONSTRUCTED AT ALL. `m27-live-workshop` and `k26-live-workshop` are the stage-8,
 * -9 and -17 rows of a real 270-row workshop as the API serves them, and their entries in the golden
 * are what `GET /design-workshops/{id}/market-analysis` and `.../cost-integrity` answered for those
 * same rows. Every synthetic case above pins a seam; these two pin the thing itself — ten survey
 * responses, four price bands, twelve SWOT points, four cost sheets and fifty cost lines, including a
 * sheet whose declared 55% margin its own price and cost put at 122.2%. A port can satisfy a table
 * built by the person who wrote it and still disagree with the server about a workshop.
 */
class DwAnalysisParityTest {

    private val json = Json { prettyPrint = false }

    private fun resource(name: String): JsonElement {
        val stream = javaClass.getResourceAsStream("/$name")
            ?: error("$name is missing from the test resources; the parity table is the test.")
        return json.parseToJsonElement(stream.reader(Charsets.UTF_8).use { it.readText() })
    }

    /** Every case computed HERE, keyed exactly as the golden keys it. */
    private fun computeAll(table: JsonObject): Map<String, JsonElement> {
        val out = LinkedHashMap<String, JsonElement>()

        for (case in table.getValue("market").jsonArray) {
            val row = case.jsonObject
            out["market/" + row.getValue("name").content()] = DwMarketAnalysis.payload(
                DwMarketAnalysis.analyse(
                    responses = row.rows("responses"),
                    competitors = row.rows("competitors"),
                    bands = row.rows("bands"),
                    swot = row.rows("swot"),
                )
            )
        }

        for (case in table.getValue("competitorPositions").jsonArray) {
            val row = case.jsonObject
            val observations = row.getValue("observations").jsonArray.map { entry ->
                val o = entry.jsonObject
                DwPriceObservation(
                    amount = o.getValue("amount").jsonPrimitiveContent().toDouble(),
                    category = o.getValue("category").content(),
                    source = o.getValue("source").content(),
                    group = o.getValue("group").content(),
                    label = o.getValue("label").content(),
                )
            }
            val placed = DwMarketAnalysis.positionCompetitors(row.rows("competitors"), observations)
            out["competitorPositions/" + row.getValue("name").content()] = JsonArray(
                placed.map { competitor ->
                    buildJsonObject {
                        put("name", competitor.name)
                        put("seller", competitor.seller)
                        put("category", competitor.category)
                        put("price", competitor.price)
                        put(
                            "percentile",
                            competitor.percentile?.let { JsonPrimitive(DwPy.round(it, 4)) } ?: JsonNull
                        )
                        put(
                            "versusMedian",
                            competitor.versusMedian?.let { JsonPrimitive(DwPy.round(it, 2)) } ?: JsonNull
                        )
                        put("note", competitor.note)
                    }
                }
            )
        }

        for (case in table.getValue("cost").jsonArray) {
            val row = case.jsonObject
            val labels = row.getValue("labels").jsonObject.mapValues { it.value.content() }
            out["cost/" + row.getValue("name").content()] = DwCostIntegrity.payload(
                DwCostIntegrity.analyse(
                    sheets = row.rows("sheets"),
                    materialLines = row.rows("materialLines"),
                    labourLines = row.rows("labourLines"),
                    labels = labels,
                )
            )
        }
        return out
    }

    @Test
    fun `every case matches the payload the Python produced for it`() {
        val table = resource("dw-analysis-cases.json").jsonObject
        val golden = resource("dw-analysis-expected.json").jsonObject
        val computed = computeAll(table)

        // Written out so the same run can be diffed against a LIVE Python execution rather than only
        // against the frozen copy. The frozen copy is what makes this test runnable offline; the live
        // diff is what proves the frozen copy is still what Python says.
        runCatching {
            val dump = File("build/parity/kotlin-analysis.json").absoluteFile
            dump.parentFile?.mkdirs()
            dump.writeText(
                json.encodeToString(
                    kotlinx.serialization.json.JsonObject.serializer(),
                    JsonObject(computed.toSortedMap())
                ),
                Charsets.UTF_8,
            )
            println("parity dump: $dump")
        }

        assertEquals(
            "the case table and the golden must describe the same cases",
            golden.keys.sorted(), computed.keys.sorted()
        )

        val problems = ArrayList<String>()
        val failedCases = LinkedHashSet<String>()
        for ((key, expected) in golden) {
            val before = problems.size
            diff(key, expected, computed.getValue(key), problems)
            if (problems.size != before) failedCases.add(key)
        }

        println("parity: ${computed.size} cases compared, ${problems.size} differing leaves")
        assertTrue(
            "PARITY BROKEN — ${problems.size} differing leaf value(s) across " +
                "${failedCases.size} of ${computed.size} cases.\n" +
                problems.take(40).joinToString("\n"),
            problems.isEmpty()
        )
    }

    /**
     * The six heads pinned against the BUNDLED registry, not against the author's memory.
     *
     * `totalCost` is a SUM the registry declares, and [DwCostIntegrity.sumCostHeads] restates the list
     * so the module stays free of the registry. A head added on the server would otherwise be left
     * silently out of the roll-up on the one client that cannot ask the server what the list is.
     */
    @Test
    fun `the six cost heads are the ones the shipped registry declares`() {
        val asset = File("src/main/assets/design-workshop-schema.json")
        // The unit test's working directory is the module, but do not fail the parity suite over a
        // path: an absent asset is a build-layout question, not a defect in the port.
        if (!asset.exists()) return
        val schema = Json { ignoreUnknownKeys = true }
            .decodeFromString(SchemaResponse.serializer(), asset.readText(Charsets.UTF_8))
        val declared = schema.stages
            .firstOrNull { it.key == "COSTING_MARKET_LINKAGE" }
            ?.entities?.firstOrNull { it.key == "costSheet" }
            ?.field("totalCost")
            ?.derivedFrom
        assertEquals(DwCostIntegrity.COST_HEADS, declared)
    }

    // ── The comparison ───────────────────────────────────────────────────────────────────────────

    private fun JsonElement.content(): String = (this as JsonPrimitive).content

    private fun JsonElement.jsonPrimitiveContent(): String = (this as JsonPrimitive).content

    private fun JsonObject.rows(key: String): List<DwDataRow> =
        getValue(key).jsonArray.map { it.jsonObject }

    /**
     * Leaf-by-leaf, and STRICT about two things `==` is not.
     *
     * A number is compared through [java.lang.Double.compare], which keeps -0.0 and 0.0 apart where
     * `==` merges them — case `m10` exists precisely because the two implementations can disagree
     * about which one a maximum is, and a comparison that could not see the difference would call the
     * disagreement a pass. Whether the literal carries a fraction is compared as well, because
     * Python writes `8` for an int and `900.0` for a float, and a count that arrived as a float is a
     * different payload even when it is the same quantity.
     */
    private fun diff(path: String, expected: JsonElement, actual: JsonElement, out: MutableList<String>) {
        if (expected is JsonObject && actual is JsonObject) {
            for (key in (expected.keys + actual.keys).sorted()) {
                val left = expected[key]
                val right = actual[key]
                when {
                    left == null -> out.add("$path/$key: python <absent>, kotlin $right")
                    right == null -> out.add("$path/$key: python $left, kotlin <absent>")
                    else -> diff("$path/$key", left, right, out)
                }
            }
            return
        }
        if (expected is JsonArray && actual is JsonArray) {
            if (expected.size != actual.size) {
                out.add("$path: python has ${expected.size} item(s), kotlin ${actual.size}")
                return
            }
            expected.forEachIndexed { index, item -> diff("$path[$index]", item, actual[index], out) }
            return
        }
        if (expected == JsonNull || actual == JsonNull) {
            if (expected != actual) out.add("$path: python $expected, kotlin $actual")
            return
        }
        val left = expected as? JsonPrimitive
        val right = actual as? JsonPrimitive
        if (left == null || right == null) {
            out.add("$path: python $expected, kotlin $actual")
            return
        }
        if (left.isString != right.isString) {
            out.add("$path: python ${if (left.isString) "string" else "literal"} ${left.content}, " +
                "kotlin ${if (right.isString) "string" else "literal"} ${right.content}")
            return
        }
        if (left.isString) {
            if (left.content != right.content) {
                out.add("$path: python ${quote(left.content)}, kotlin ${quote(right.content)}")
            }
            return
        }
        if (left.content == "true" || left.content == "false" ||
            right.content == "true" || right.content == "false"
        ) {
            if (left.content != right.content) {
                out.add("$path: python ${left.content}, kotlin ${right.content}")
            }
            return
        }
        val leftNumber = left.content.toDouble()
        val rightNumber = right.content.toDouble()
        if (java.lang.Double.compare(leftNumber, rightNumber) != 0) {
            out.add("$path: python ${left.content}, kotlin ${right.content}")
            return
        }
        if (isFractional(left.content) != isFractional(right.content)) {
            out.add("$path: python ${left.content} (${kind(left.content)}), " +
                "kotlin ${right.content} (${kind(right.content)})")
        }
    }

    private fun isFractional(literal: String): Boolean =
        literal.contains('.') || literal.contains('e') || literal.contains('E')

    private fun kind(literal: String): String = if (isFractional(literal)) "float" else "int"

    /** Escapes the astral and combining characters so a failure message is readable in a terminal. */
    private fun quote(text: String): String = buildString {
        append('"')
        for (ch in text) {
            if (ch.code in 32..126) append(ch) else append("\\u%04x".format(ch.code))
        }
        append('"')
    }
}
