apiVersion: v1
kind: Namespace
metadata:
  name: design-workshop-staging
  labels:
    app.kubernetes.io/part-of: design-workshop
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
