pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()

        /**
         * THE SPEECH ENGINE, VENDORED, BECAUSE IT CANNOT BE RESOLVED ANY OTHER WAY.
         *
         * `docs/ASR-RUNTIME-MEASUREMENT.md` §1 asked the Gradle resolver itself — six plausible
         * coordinates for `sherpa-onnx`, six live 404s from `google()` and `mavenCentral()`, and
         * Maven Central's own search index answering `numFound: 0`. Upstream publishes the Android
         * build as a **GitHub release asset** and nothing else. That document listed three ways
         * forward and called each of them somebody's decision; this is the first of them — vendor
         * the binary — taken deliberately and recorded here rather than in a commit message.
         *
         * `repositoriesMode` above is `FAIL_ON_PROJECT_REPOS`, so a `repositories { flatDir { … } }`
         * block inside `app/build.gradle.kts` would fail the build outright. That is the reason the
         * declaration is HERE and not beside the dependency that uses it: the settings file is the
         * only place this project permits a repository to be declared, and weakening the mode to
         * put it next to its dependency would remove the guard that keeps every other dependency
         * coming from a repository the whole project agreed on.
         *
         * A `flatDir` repository resolves by FILE NAME and carries no POM, so it brings no
         * transitive dependencies with it. For this artifact that is correct rather than a
         * limitation — the static-link AAR is self-contained (`docs/ASR-RUNTIME-MEASUREMENT.md` §3
         * read its central directory: four `.so` files per ABI, one `classes.jar`, and nothing
         * else) — but it is exactly the trap a future reader falls into if they vendor something
         * that DOES have dependencies and finds it failing at run time rather than at build time.
         */
        flatDir { dirs("app/libs") }
    }
}

rootProject.name = "DesignPrototypeWorkshopAndroid"
include(":app")

/**
 * THE TRACE ENGINE, VENDORED AS FOUR PLAIN KOTLIN/JVM MODULES.
 *
 * These four came verbatim from `F:/Offline-Tracer/android/` and are recorded file by file, with a
 * SHA-256 each, in `android/UPSTREAM-MANIFEST-KOTLIN.txt`. That file is the record of what was
 * taken and when; this comment is the record of WHY they are shaped the way they are.
 *
 * THEY ARE `org.jetbrains.kotlin.jvm`, NOT `com.android.library`, AND THAT IS THE POINT.
 * There is no Android API anywhere in the 101 Kotlin files. Outside `kotlin.*` and the engine's own
 * `com.offlinetracer.*` packages they import exactly thirteen JDK types — `java.io.File`,
 * `java.io.ByteArrayOutputStream`, seven `java.util.concurrent` types (three atomics,
 * `CountDownLatch`, `Executors`, `ExecutorService`, `RejectedExecutionException`) and four
 * `java.util.zip` types (`CRC32`, `Deflater`, `DeflaterOutputStream`, `Inflater`) — plus
 * `kotlinx.serialization`. Every one of those is present on `minSdk = 26`. Nothing imports
 * `android.*`, and nothing imports `java.awt` either, which is what would have made this engine
 * desktop-only instead of portable.
 *
 * What that buys is the reason to keep it. The 47 unit-test files that came with these modules
 * (`:core-imaging` 17, `:core-vector` 8, `:core-pipeline` 12, `:core-export` 10) run on the desktop
 * JVM with no emulator, no device and no Android SDK involved:
 *
 *     .\gradlew.bat :core-imaging:test :core-vector:test :core-pipeline:test :core-export:test
 *
 * On 2026-08-27 that was 760 tests, 0 failures, 0 skipped — 315 / 124 / 248 / 73 by module, 8.8
 * seconds of actual test execution inside a six-minute cold build that is almost entirely compiling
 * them. Four of those 760 are `:core-pipeline`'s `ParityTest`, which replays fixtures generated by
 * the TypeScript engine (`docs/fixtures/`, vendored alongside these modules and listed in the
 * manifest) and asserts the Kotlin produces the same numbers. That is the only mechanical check in
 * this repository that the handset and the browser draw the same thing, and making these Android
 * libraries would have traded it for nothing at all. Only `:app` depends on Android.
 *
 * `:core-native`, the fifth module upstream has, is deliberately NOT vendored. It is an optional
 * SIMD accelerator, and `:core-imaging` holds the reference implementation of every kernel in it;
 * upstream's own settings file records that deleting it "would cost speed and change no output".
 * Bringing it would have meant NDK toolchains and per-ABI native builds in a repository that has
 * neither, to make a trace faster that has not yet been measured as too slow.
 *
 * These declare no repositories of their own, so `FAIL_ON_PROJECT_REPOS` above is untouched by
 * them: `kotlinx-serialization-json`, the single external dependency in the four, resolves from the
 * `mavenCentral()` already declared here at the version `:app` already uses.
 */
include(":core-imaging")
include(":core-vector")
include(":core-pipeline")
include(":core-export")
