package com.designprototype.workshop.data

import kotlin.math.abs
import kotlin.math.floor
import kotlin.math.max

/**
 * A QR symbol, drawn on this handset, from nothing but this file — the port of `frontend/lib/qrEncode.ts`.
 *
 * WHY THIS IS HAND-WRITTEN AND NOT A DEPENDENCY, AND WHY THAT ARGUMENT IS STRONGER HERE. The web
 * module's header makes the case: the codes are printed on artisan cards and prototype tags in a
 * courtyard, from a machine that has had no signal for three days, so a hosted chart API is out; and
 * a QR library is a transitive dependency tree, and its future CVEs and its future breaking major,
 * bought under a feature whose entire specification is three hundred lines of ISO 18004 that was
 * frozen in 2000 and will not change again. On Android the same purchase is dearer still — a library
 * here is method count in a 64K-limited dex, a second copy of the same frozen standard, and a Play
 * Store review of a transitive AAR nobody in this repository has read. A stable standard implemented
 * once, in two languages that agree module for module, is the cheaper thing to own.
 *
 * SO THIS IS DELIBERATELY NOT A GENERAL QR LIBRARY EITHER, and the limits are refusals rather than
 * gaps. They are the web's limits exactly, because a card printed by the handset and a card printed
 * by the browser have to be the same card:
 *
 *  - **Alphanumeric mode only.** The 45-character set (digits, capitals, space and eight punctuation
 *    marks) at 5.5 bits per character. The workshop-code grammar emits nothing outside it — that is
 *    why the payload is upper-case and colon-separated rather than free text. Byte mode would double
 *    the symbol for no gain and would invite arbitrary strings, including a person's name, into a
 *    code this file promises never to carry one of.
 *  - **Versions 1 to 6 only** (21x21 to 41x41). Version 7 upwards has to carry an extra 18-bit
 *    version block in two corners, and no reference this application generates comes close to
 *    version 6's 108 alphanumeric characters at level Q. [encode] REFUSES a longer string rather
 *    than silently truncating it: a truncated identifier scans cleanly and resolves to the wrong
 *    record, which is the single failure this whole feature exists to prevent.
 *
 * VERIFIED AGAINST AN INDEPENDENT ENCODER, not against itself and not against the TypeScript alone.
 * `DwQrEncodeTest` carries the same reference matrices `frontend/e2e/workshop-codes.spec.ts` uses —
 * every module of all eight masks of seven symbols, generated by reportlab's QR encoder, a different
 * implementation in a different language — plus the values only the web can supply: the penalty
 * scores, the mask [encode] settles on, and the SVG path character for character. Mask SELECTION has
 * no independent oracle, because reportlab's penalty scorer has two departures from the standard
 * (its vertical rule-3 pass compares a tuple against a list and so never fires, and it looks only for
 * the dark-first finder-lookalike), so [penalty] is `internal` and pinned by value against the web's
 * own scores instead. Both choices produce a legal, scannable symbol; ours implements the rules as
 * written, and it must implement them the same way the browser does or the two clients print
 * different cards for one record.
 *
 * PURE, in the sense [DwMarketAnalysis] is: no Android, no Compose, no network, no Bitmap. It returns
 * a matrix of booleans and, for convenience, an SVG path string. The on-screen preview and the
 * printed sheet render from the same matrix on both clients, so what a designer checks on the screen
 * is what the printer puts on the card.
 *
 * ── WHERE KOTLIN'S OBVIOUS SPELLING IS NOT JAVASCRIPT'S ───────────────────────────────────────
 *
 * [DwPy] is not used here and that is deliberate, not an oversight: it is Python's semantics, and the
 * reference for this module is the BROWSER. The three places the two languages part company are
 * marked in the code, and every one of them changes the symbol rather than crashing:
 *
 *  - **Rule 4 of [penalty] divides in DOUBLE.** `dark * 100 / (size * size)` is integer division in
 *    Kotlin and float division in JavaScript. The two disagree only on a narrow band of dark
 *    fractions — measured at one mask in ninety-six thousand, see [penalty] — but a disagreement
 *    there picks a different mask, and the handset then prints a symbol the browser would not have
 *    drawn: legal, scannable, and not the card already glued to the prototype. It is the one guard
 *    in this file that the parity golden does NOT catch, which is why the argument for it is
 *    written out where it is made rather than left to a test to assert.
 *  - **Every integer written out is written by `Int.toString`** — a string template in the refusal
 *    sentence, `StringBuilder.append(Int)` in the path — and never by `String.format`.
 *    `String.format("%d", …)` uses `Locale.getDefault(Locale.Category.FORMAT)`, and a handset set to
 *    a locale carrying a non-Latin numbering system renders `%d` in Devanagari or Odia digits. An
 *    SVG path reading "M१२ ५h३v1h-३z" is not a path, and the card comes out of the printer blank on
 *    exactly the devices this application is built for.
 *  - **String iteration.** JavaScript's `for…of` walks CODE POINTS and Kotlin's `for (c in text)`
 *    walks UTF-16 code UNITS. The answers coincide here only because all 45 alphanumeric characters
 *    are ASCII, so any code point outside the set contains at least one code unit outside it too;
 *    see [isAlphanumeric], where that coincidence is stated rather than relied on silently.
 */

/**
 * Error correction levels, and the two bits each contributes to the format information block.
 *
 * The bits are NOT an L-to-H ordering — L is 1 and M is 0 — which is the transcription slip that
 * produces a symbol whose format block claims the wrong level, and therefore a symbol a scanner
 * decodes with the wrong Reed-Solomon parameters and rejects as damaged.
 */
enum class DwQrEccLevel(val formatBits: Int) {
    L(0b01),
    M(0b00),
    Q(0b11),
    H(0b10),
}

/** Why a string could not be turned into a symbol. */
enum class DwQrRefusal {
    /** A character outside the 45 alphanumeric mode carries. */
    NOT_ALPHANUMERIC,

    /** Longer than version 6 holds at the requested level. */
    TOO_LONG,

    /** Nothing to encode. */
    EMPTY,
}

/**
 * Why a string could not be turned into a symbol. Carries a sentence fit to show a designer.
 *
 * The message is the WEB'S message, word for word, and `DwQrEncodeTest` pins it. A designer who
 * prints a sheet from the laptop and a sheet from the handset must be told the same thing about the
 * same code; two different sentences for one refusal reads as two different faults.
 */
class DwQrEncodeException(
    val reason: DwQrRefusal,
    message: String,
) : IllegalArgumentException(message)

/**
 * One drawn symbol.
 *
 * Not a `data class`: [matrix] is an array, so the generated `equals` would compare it by IDENTITY
 * while claiming to compare symbols by value — a comparison that silently answers "different" for
 * two identical symbols is worse than none, and the test renders the matrix to a string to compare
 * it anyway.
 */
class DwQrSymbol(
    /** `matrix[row][column]` — true is a dark module. Row 0 is the top. */
    val matrix: Array<BooleanArray>,
    /** Modules per side: 17 + 4 x version. */
    val size: Int,
    val version: Int,
    val level: DwQrEccLevel,
    /** Which of the eight masks was applied. Exposed so a test can pin it. */
    val mask: Int,
)

/**
 * The dark modules of a symbol as one SVG path, with the quiet zone already accounted for.
 *
 * The [quiet] zone is included in [extent] rather than left to the caller, because a symbol printed
 * hard against a card's border does not scan and there is no way to see that on screen.
 */
class DwQrSvg(
    val path: String,
    /** Side length of the drawing including the quiet zone, in module units — use as the viewBox. */
    val extent: Int,
    val symbol: DwQrSymbol,
)

object DwQrEncode {

    /** The 45 characters alphanumeric mode can carry, in the order that defines their values. */
    private const val ALPHANUMERIC = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ \$%*+-./:"

    /**
     * The smallest and largest symbols this file will build. See the header: the ceiling is a
     * refusal, not an omission, and [MAX_VERSION] may not be raised without adding the version
     * information block that versions 7 and up require in two corners.
     */
    const val MIN_VERSION = 1
    const val MAX_VERSION = 6

    /** Total codewords (data + error correction) in versions 1-6. */
    private val TOTAL_CODEWORDS = intArrayOf(26, 44, 70, 100, 134, 172)

    /**
     * Alignment pattern centre coordinates per version. Version 1 has none; 2-6 have a single extra
     * pattern whose centre is the second coordinate in each pair.
     */
    private val ALIGNMENT_CENTRES = arrayOf(
        intArrayOf(),
        intArrayOf(6, 18),
        intArrayOf(6, 22),
        intArrayOf(6, 26),
        intArrayOf(6, 30),
        intArrayOf(6, 34),
    )

    /**
     * How a version's codewords are cut into Reed-Solomon blocks, per error correction level.
     *
     * `[ecPerBlock, group1Blocks, group1DataCodewords, group2Blocks, group2DataCodewords]`. Group 2
     * exists only where the standard splits a version into blocks of two different sizes (5-Q and
     * 5-H here); its data count is always exactly one more than group 1's.
     *
     * Written out rather than derived, because every row is checkable against ISO 18004 table 9 by
     * arithmetic: (g1Blocks x (g1Data + ec)) + (g2Blocks x (g2Data + ec)) must equal
     * [TOTAL_CODEWORDS] for that version. `DwQrEncodeTest` asserts exactly that for all 24 rows,
     * which is what turns a transcription slip into a red test instead of an unreadable card.
     */
    private val BLOCKS: Map<DwQrEccLevel, List<IntArray>> = mapOf(
        //                          ec  g1  g1data  g2  g2data
        DwQrEccLevel.L to listOf(
            intArrayOf(7, 1, 19, 0, 0),
            intArrayOf(10, 1, 34, 0, 0),
            intArrayOf(15, 1, 55, 0, 0),
            intArrayOf(20, 1, 80, 0, 0),
            intArrayOf(26, 1, 108, 0, 0),
            intArrayOf(18, 2, 68, 0, 0),
        ),
        DwQrEccLevel.M to listOf(
            intArrayOf(10, 1, 16, 0, 0),
            intArrayOf(16, 1, 28, 0, 0),
            intArrayOf(26, 1, 44, 0, 0),
            intArrayOf(18, 2, 32, 0, 0),
            intArrayOf(24, 2, 43, 0, 0),
            intArrayOf(16, 4, 27, 0, 0),
        ),
        DwQrEccLevel.Q to listOf(
            intArrayOf(13, 1, 13, 0, 0),
            intArrayOf(22, 1, 22, 0, 0),
            intArrayOf(18, 2, 17, 0, 0),
            intArrayOf(26, 2, 24, 0, 0),
            intArrayOf(18, 2, 15, 2, 16),
            intArrayOf(24, 4, 19, 0, 0),
        ),
        DwQrEccLevel.H to listOf(
            intArrayOf(17, 1, 9, 0, 0),
            intArrayOf(28, 1, 16, 0, 0),
            intArrayOf(22, 2, 13, 0, 0),
            intArrayOf(16, 4, 9, 0, 0),
            intArrayOf(22, 2, 11, 2, 12),
            intArrayOf(28, 4, 15, 0, 0),
        ),
    )

    /**
     * Bits of padding the standard adds after the last codeword, per version. Zero for version 1 and
     * seven for versions 2-6. They are written as light modules and carry nothing; omitting them
     * leaves seven modules of the symbol undefined, which some decoders read and some do not.
     */
    private val REMAINDER_BITS = intArrayOf(0, 7, 7, 7, 7, 7)

    /**
     * The block table row for one version at one level, as the standard tabulates it.
     *
     * Returns the table's OWN array, not a copy — this is on the path of every symbol drawn, and a
     * defensive copy per call would allocate once per block per card on a print sheet. Nothing may
     * write through it. `internal` so `DwQrEncodeTest` can check all 24 rows against ISO 18004 by
     * arithmetic, which is the claim the comment on [BLOCKS] makes and would otherwise only assert.
     */
    internal fun blocks(version: Int, level: DwQrEccLevel): IntArray = BLOCKS.getValue(level)[version - 1]

    /** Total codewords, data and error correction together, in one version. */
    internal fun totalCodewords(version: Int): Int = TOTAL_CODEWORDS[version - 1]

    // ----------------------------------------------------------------------------------
    // GF(256) — the field Reed-Solomon works in
    //
    // Built once at class load from the primitive polynomial x^8+x^4+x^3+x^2+1 (0x11D), which is the
    // one QR specifies. Two 256-entry tables turn every field multiplication into two lookups and an
    // add.
    //
    // IntArray, not ByteArray, unlike [DwImageQuality]'s greyscale plane. There the width was the
    // point (a full-resolution luma plane is megabytes on the device that can least afford them);
    // here the two tables are 768 entries between them, and a JVM `Byte` is SIGNED — every read
    // would need `and 0xFF` and the one place that forgot it would put a negative index into
    // GF_EXP and take the print sheet down with an ArrayIndexOutOfBoundsException.
    // ----------------------------------------------------------------------------------

    private val GF_EXP = IntArray(512)
    private val GF_LOG = IntArray(256)

    init {
        var x = 1
        for (i in 0 until 255) {
            GF_EXP[i] = x
            GF_LOG[x] = i
            x = x shl 1
            if (x and 0x100 != 0) x = x xor 0x11D
        }
        // The tail repeats the table so an exponent sum up to 508 needs no modulo in the hot loop.
        for (i in 255 until 512) GF_EXP[i] = GF_EXP[i - 255]
    }

    private fun gfMultiply(a: Int, b: Int): Int {
        if (a == 0 || b == 0) return 0
        return GF_EXP[GF_LOG[a] + GF_LOG[b]]
    }

    /** The generator polynomial whose roots are a^0…a^(degree-1), as coefficients high-order first. */
    private fun generatorPolynomial(degree: Int): IntArray {
        var poly = intArrayOf(1)
        for (i in 0 until degree) {
            val next = IntArray(poly.size + 1)
            for (j in poly.indices) {
                next[j] = next[j] xor poly[j]
                next[j + 1] = next[j + 1] xor gfMultiply(poly[j], GF_EXP[i])
            }
            poly = next
        }
        return poly
    }

    /** The `ecCount` error correction codewords for one block of data codewords. */
    private fun errorCorrectionFor(data: IntArray, ecCount: Int): IntArray {
        val generator = generatorPolynomial(ecCount)
        val remainder = IntArray(ecCount)
        for (byte in data) {
            val factor = byte xor remainder[0]
            // `copyWithin(0, 1)` in the web: shift the whole remainder one place towards the front.
            // The source and destination overlap, which is exactly what System.arraycopy is
            // specified to handle correctly; a hand-rolled backwards loop here would smear the
            // first element over the block and produce error correction that a scanner reads as
            // damage on every card.
            System.arraycopy(remainder, 1, remainder, 0, ecCount - 1)
            remainder[ecCount - 1] = 0
            if (factor != 0) {
                // generator[0] is always 1, so the leading term is what was just shifted out.
                for (i in 0 until ecCount) remainder[i] = remainder[i] xor gfMultiply(generator[i + 1], factor)
            }
        }
        return remainder
    }

    // ----------------------------------------------------------------------------------
    // Bit assembly
    // ----------------------------------------------------------------------------------

    /**
     * The bit stream a symbol's data segment is assembled in, one bit per entry.
     *
     * A bit at a time rather than an accumulator over bytes because the standard's fields do not sit
     * on byte boundaries: 4 mode bits, 9 count bits and then 11 bits per character pair. The whole
     * point of the class is that no caller ever has to know where a byte ends.
     */
    private class Bits {
        private val bits = ArrayList<Boolean>(256)

        val size: Int get() = bits.size

        fun put(value: Int, length: Int) {
            // A negative length writes nothing, which is what the terminator relies on when the
            // capacity is exactly full. `for (i in -1 downTo 0)` is an empty range, same as the
            // web's `for (let i = -1; i >= 0; i--)`.
            for (i in length - 1 downTo 0) bits.add((value ushr i) and 1 == 1)
        }

        /** Pad to a whole number of bytes and return them, each 0-255. */
        fun toBytes(): IntArray {
            val out = IntArray((bits.size + 7) / 8)
            for ((index, bit) in bits.withIndex()) {
                if (bit) out[index ushr 3] = out[index ushr 3] or (0x80 ushr (index and 7))
            }
            return out
        }
    }

    /**
     * Whether every character of [text] can be carried by alphanumeric mode.
     *
     * The web walks CODE POINTS (`for…of`) and this walks UTF-16 code UNITS, and the two agree only
     * because all 45 characters in the set are ASCII: a code point outside the set — an emoji, a
     * Devanagari letter, half of a surrogate pair — always contains at least one code unit outside
     * it too, so both spellings answer false. That is a fact about this particular alphabet, not a
     * general equivalence, and it stops holding the moment anyone widens [ALPHANUMERIC].
     */
    fun isAlphanumeric(text: String): Boolean {
        for (character in text) {
            if (!ALPHANUMERIC.contains(character)) return false
        }
        return true
    }

    /**
     * How many alphanumeric characters fit in one version at one level.
     *
     * Derived from the block table rather than tabulated separately, so a capacity and a block layout
     * cannot drift apart: two characters share 11 bits, a lone trailing one takes 6, and the header
     * is 4 mode bits plus a 9-bit character count (9 for versions 1-9, which is every version here).
     */
    fun capacity(version: Int, level: DwQrEccLevel): Int {
        val (_, g1Blocks, g1Data, g2Blocks, g2Data) = blocks(version, level)
        val dataBits = (g1Blocks * g1Data + g2Blocks * g2Data) * 8 - 4 - 9
        // Int division rather than `floor(dataBits / 11.0)`: dataBits is positive for every row of
        // the table, and for a positive numerator truncation towards zero IS the web's Math.floor.
        val pairs = dataBits / 11
        // A leftover of 6 bits or more carries one more character; fewer carries none.
        return pairs * 2 + if (dataBits - pairs * 11 >= 6) 1 else 0
    }

    // ----------------------------------------------------------------------------------
    // The symbol
    // ----------------------------------------------------------------------------------

    private fun newMatrix(size: Int): Array<BooleanArray> = Array(size) { BooleanArray(size) }

    /** Draw one 7x7 finder pattern with its light separator, anchored at the given top-left corner. */
    private fun drawFinder(matrix: Array<BooleanArray>, reserved: Array<BooleanArray>, top: Int, left: Int) {
        val size = matrix.size
        for (row in -1..7) {
            for (column in -1..7) {
                val r = top + row
                val c = left + column
                if (r < 0 || r >= size || c < 0 || c >= size) continue
                val ring = max(abs(row - 3), abs(column - 3))
                matrix[r][c] = ring != 2 && ring <= 3
                reserved[r][c] = true
            }
        }
    }

    /** Every module that carries a function pattern or a reserved block, drawn before any data. */
    private fun drawFunctionPatterns(matrix: Array<BooleanArray>, reserved: Array<BooleanArray>, version: Int) {
        val size = matrix.size

        drawFinder(matrix, reserved, 0, 0)
        drawFinder(matrix, reserved, 0, size - 7)
        drawFinder(matrix, reserved, size - 7, 0)

        // Timing patterns: alternating modules along row 6 and column 6, between the finders.
        for (i in 8 until size - 8) {
            val dark = i % 2 == 0
            matrix[6][i] = dark
            reserved[6][i] = true
            matrix[i][6] = dark
            reserved[i][6] = true
        }

        // Alignment patterns, at every combination of the version's centres except the three that
        // would land on a finder.
        val centres = ALIGNMENT_CENTRES[version - 1]
        for (centreRow in centres) {
            for (centreColumn in centres) {
                val onFinder =
                    (centreRow == 6 && centreColumn == 6) ||
                        (centreRow == 6 && centreColumn == size - 7) ||
                        (centreRow == size - 7 && centreColumn == 6)
                if (onFinder) continue
                for (row in -2..2) {
                    for (column in -2..2) {
                        matrix[centreRow + row][centreColumn + column] = max(abs(row), abs(column)) != 1
                        reserved[centreRow + row][centreColumn + column] = true
                    }
                }
            }
        }

        // The format information blocks are written after masking, but their modules must be
        // reserved now or the data placement would run straight through them.
        for (i in 0..8) {
            if (i != 6) {
                reserved[8][i] = true
                reserved[i][8] = true
            }
        }
        for (i in 0 until 8) {
            reserved[8][size - 1 - i] = true
            reserved[size - 1 - i][8] = true
        }
        // The one module that is always dark, immediately above the bottom-left finder's format strip.
        matrix[size - 8][8] = true
        reserved[size - 8][8] = true
    }

    /** The 15-bit BCH-protected format information for a level and mask. */
    private fun formatBits(level: DwQrEccLevel, mask: Int): Int {
        val data = (level.formatBits shl 3) or mask
        var remainder = data
        // `ushr` rather than `shr`: the web's `>>>` is the unsigned shift, and although `remainder`
        // never grows past fifteen bits here, spelling it as the signed shift would be one refactor
        // away from sign-extending a value into a generator polynomial nobody would think to check.
        for (i in 0 until 10) remainder = (remainder shl 1) xor ((remainder ushr 9) * 0x537)
        return (((data shl 10) or remainder) xor 0x5412) and 0x7FFF
    }

    private fun drawFormat(matrix: Array<BooleanArray>, level: DwQrEccLevel, mask: Int) {
        val size = matrix.size
        val bits = formatBits(level, mask)
        fun bit(index: Int): Boolean = ((bits ushr index) and 1) == 1

        // First copy: down the left of the top-left finder, then right along row 8.
        for (i in 0..5) matrix[i][8] = bit(i)
        matrix[7][8] = bit(6)
        matrix[8][8] = bit(7)
        matrix[8][7] = bit(8)
        for (i in 9 until 15) matrix[8][14 - i] = bit(i)

        // Second copy: right along row 8 from the far edge, then up the bottom-left finder's column.
        for (i in 0 until 8) matrix[8][size - 1 - i] = bit(i)
        for (i in 8 until 15) matrix[size - 15 + i][8] = bit(i)
    }

    /** Whether mask [mask] inverts the module at (row, column). Straight from ISO 18004 table 10. */
    private fun maskInverts(mask: Int, row: Int, column: Int): Boolean = when (mask) {
        0 -> (row + column) % 2 == 0
        1 -> row % 2 == 0
        2 -> column % 3 == 0
        3 -> (row + column) % 3 == 0
        4 -> (row / 2 + column / 3) % 2 == 0
        5 -> ((row * column) % 2) + ((row * column) % 3) == 0
        6 -> (((row * column) % 2) + ((row * column) % 3)) % 2 == 0
        else -> (((row + column) % 2) + ((row * column) % 3)) % 2 == 0
    }

    /**
     * The four penalty rules, as written in the standard, summed. Lower is better.
     *
     * The point of them is that a symbol should not contain large flat areas or anything that looks
     * like a finder pattern, because both make a scanner work harder — and the scanner here is a
     * handset camera held over a printed card in a courtyard, which is the least forgiving reading
     * condition this application has.
     *
     * `internal` rather than private, alone among the drawing helpers, because it is the one part of
     * the encoder with NO independent oracle: the reportlab fixture pins all eight masks but
     * deliberately does not pin which one wins, since reportlab's own scorer departs from the
     * standard in two places. So the parity test reads these scores out directly and compares them
     * with the browser's, case by case. Pinning only the winning mask would let two compensating
     * errors in different rules agree on an argmin and hide from the test forever.
     */
    internal fun penalty(matrix: Array<BooleanArray>): Int {
        val size = matrix.size
        var score = 0

        // Rule 1 — runs of five or more identical modules, in both directions.
        for (outer in 0 until size) {
            for (horizontal in listOf(true, false)) {
                var runValue = if (horizontal) matrix[outer][0] else matrix[0][outer]
                var runLength = 1
                for (inner in 1 until size) {
                    val value = if (horizontal) matrix[outer][inner] else matrix[inner][outer]
                    if (value == runValue) {
                        runLength++
                        continue
                    }
                    if (runLength >= 5) score += runLength - 2
                    runValue = value
                    runLength = 1
                }
                if (runLength >= 5) score += runLength - 2
            }
        }

        // Rule 2 — every 2x2 block of one colour.
        for (row in 0 until size - 1) {
            for (column in 0 until size - 1) {
                val value = matrix[row][column]
                if (value == matrix[row][column + 1] &&
                    value == matrix[row + 1][column] &&
                    value == matrix[row + 1][column + 1]
                ) {
                    score += 3
                }
            }
        }

        // Rule 3 — anything a scanner could mistake for a finder pattern: 1011101 with four light
        // modules on either side. BOTH orientations count, in both directions.
        val forward = booleanArrayOf(true, false, true, true, true, false, true, false, false, false, false)
        val backward = forward.reversedArray()
        for (outer in 0 until size) {
            for (horizontal in listOf(true, false)) {
                var start = 0
                while (start + 11 <= size) {
                    var matchesForward = true
                    var matchesBackward = true
                    for (offset in 0 until 11) {
                        val value = if (horizontal) matrix[outer][start + offset] else matrix[start + offset][outer]
                        if (value != forward[offset]) matchesForward = false
                        if (value != backward[offset]) matchesBackward = false
                    }
                    if (matchesForward) score += 40
                    if (matchesBackward) score += 40
                    start++
                }
            }
        }

        // Rule 4 — how far the proportion of dark modules strays from half.
        var dark = 0
        for (row in matrix) for (value in row) if (value) dark++
        // DOUBLE division, and the `.0` is the whole point: `dark * 100 / (size * size)` is INTEGER
        // division in Kotlin and float division in JavaScript. Truncation only ever drags the
        // percentage AWAY from fifty on the low side and TOWARDS it on the high side, so the two
        // spellings differ exactly when the dark fraction lands strictly between a multiple of five
        // and the next integer below fifty — a 29x29 symbol at 45.898% dark scores 0 here and 10
        // under integer division, while 45.0% and 54.9% score the same either way.
        //
        // THAT IS RARE, IT IS MEASURED, AND IT IS STILL WRITTEN THIS WAY. Over 12,000 generated
        // payloads the two terms differed on ONE mask in 96,000, and the mask a symbol settles on
        // never moved; no case in DwQrEncodeTest's golden would catch the integer spelling. The
        // reason to write it correctly anyway is the shape of the failure rather than its rate: a
        // card drawn with mask 5 where the browser would have drawn mask 3 looks perfectly right,
        // scans perfectly well, and surfaces months later as "the office sheet and the courtyard
        // sheet don't match" with nothing on either card to say which build drew it. One character
        // is a cheap price for never having that conversation.
        val percent = (dark * 100.0) / (size * size)
        score += floor(abs(percent - 50.0) / 5.0).toInt() * 10

        return score
    }

    /**
     * Turn [text] into the interleaved codeword stream the symbol carries.
     *
     * The interleaving is the part worth understanding: the blocks are woven together codeword by
     * codeword so that a smudge covering a contiguous patch of the printed symbol damages a little of
     * every block rather than destroying one of them outright. On a card that lives in a workshop,
     * that is the difference between a scan that still resolves and one that does not.
     */
    private fun buildCodewords(text: String, version: Int, level: DwQrEccLevel): IntArray {
        val (ecPerBlock, g1Blocks, g1Data, g2Blocks, g2Data) = blocks(version, level)
        val totalData = g1Blocks * g1Data + g2Blocks * g2Data

        val buffer = Bits()
        buffer.put(0b0010, 4) // alphanumeric mode indicator
        buffer.put(text.length, 9) // character count, 9 bits for versions 1-9
        var i = 0
        while (i + 1 < text.length) {
            buffer.put(ALPHANUMERIC.indexOf(text[i]) * 45 + ALPHANUMERIC.indexOf(text[i + 1]), 11)
            i += 2
        }
        if (text.length % 2 == 1) buffer.put(ALPHANUMERIC.indexOf(text[text.length - 1]), 6)

        // Terminator: up to four zero bits, fewer when the capacity is nearly full.
        buffer.put(0, minOf(4, totalData * 8 - buffer.size))
        // Pad to a byte boundary, then alternate 0xEC / 0x11 to the end. The two pad bytes are
        // specified values, not arbitrary filler — a decoder uses them to tell padding from data.
        if (buffer.size % 8 != 0) buffer.put(0, 8 - (buffer.size % 8))
        val bytes = buffer.toBytes()
        val data = IntArray(totalData)
        bytes.copyInto(data, 0, 0, minOf(bytes.size, totalData))
        for (index in bytes.size until totalData) data[index] = if ((index - bytes.size) % 2 == 0) 0xEC else 0x11

        val dataBlocks = ArrayList<IntArray>(g1Blocks + g2Blocks)
        val ecBlocks = ArrayList<IntArray>(g1Blocks + g2Blocks)
        var offset = 0
        for (block in 0 until g1Blocks + g2Blocks) {
            val length = if (block < g1Blocks) g1Data else g2Data
            // A COPY where the web takes a `subarray` view. Nothing writes through either one, so the
            // two are equivalent; the copy is spelled out so that a future reader does not add a
            // mutation here expecting it to reach `data`.
            val slice = data.copyOfRange(offset, offset + length)
            offset += length
            dataBlocks.add(slice)
            ecBlocks.add(errorCorrectionFor(slice, ecPerBlock))
        }

        val out = IntArray(totalCodewords(version))
        var written = 0
        val longestData = max(g1Data, g2Data)
        for (index in 0 until longestData) {
            for (block in dataBlocks) if (index < block.size) out[written++] = block[index]
        }
        for (index in 0 until ecPerBlock) {
            for (block in ecBlocks) out[written++] = block[index]
        }
        return out
    }

    /** Lay the codeword stream into the matrix in the standard two-column upward/downward zigzag. */
    private fun drawCodewords(
        matrix: Array<BooleanArray>,
        reserved: Array<BooleanArray>,
        codewords: IntArray,
        version: Int,
    ) {
        val size = matrix.size
        val totalBits = codewords.size * 8 + REMAINDER_BITS[version - 1]
        var bitIndex = 0

        var right = size - 1
        while (right >= 1) {
            // Column 6 is the vertical timing pattern; the pairs step over it entirely.
            val rightColumn = if (right <= 6) right - 1 else right
            for (vertical in 0 until size) {
                for (offset in 0 until 2) {
                    val column = rightColumn - offset
                    val upward = ((rightColumn + 1) and 2) == 0
                    val row = if (upward) size - 1 - vertical else vertical
                    if (reserved[row][column]) continue
                    if (bitIndex >= totalBits) continue
                    // Remainder bits past the last codeword stay light; they carry nothing.
                    val byte = bitIndex ushr 3
                    matrix[row][column] =
                        byte < codewords.size && ((codewords[byte] ushr (7 - (bitIndex and 7))) and 1) == 1
                    bitIndex++
                }
            }
            right -= 2
        }
    }

    /**
     * Build the symbol for [text] at one version, level and mask.
     *
     * Public for the parity test, which drives all eight masks against reference matrices from a
     * second implementation. Application code wants [encode], which picks both for itself.
     */
    fun buildMatrix(text: String, version: Int, level: DwQrEccLevel, mask: Int): Array<BooleanArray> {
        val size = 17 + 4 * version
        val matrix = newMatrix(size)
        val reserved = newMatrix(size)
        drawFunctionPatterns(matrix, reserved, version)
        drawCodewords(matrix, reserved, buildCodewords(text, version, level), version)
        for (row in 0 until size) {
            for (column in 0 until size) {
                if (!reserved[row][column] && maskInverts(mask, row, column)) matrix[row][column] = !matrix[row][column]
            }
        }
        drawFormat(matrix, level, mask)
        return matrix
    }

    /**
     * Encode [text] as the smallest symbol that will hold it at [level], with the mask the standard's
     * penalty rules prefer.
     *
     * Throws [DwQrEncodeException] rather than returning a degraded symbol. A caller printing forty
     * cards wants to know which one it could not draw; a caller that silently got a shorter string
     * back would print a tag that scans to a record that does not exist.
     */
    fun encode(text: String, level: DwQrEccLevel = DwQrEccLevel.Q): DwQrSymbol {
        if (text.isEmpty()) throw DwQrEncodeException(DwQrRefusal.EMPTY, "There is nothing to encode.")
        if (!isAlphanumeric(text)) {
            throw DwQrEncodeException(
                DwQrRefusal.NOT_ALPHANUMERIC,
                "This code contains characters a compact QR symbol cannot carry. Codes are upper-case letters, " +
                    "digits and the punctuation the standard allows.",
            )
        }

        var version = 0
        for (candidate in MIN_VERSION..MAX_VERSION) {
            if (text.length <= capacity(candidate, level)) {
                version = candidate
                break
            }
        }
        if (version == 0) {
            throw DwQrEncodeException(
                DwQrRefusal.TOO_LONG,
                // A string template, not String.format: `%d` under a Hindi or Odia FORMAT locale
                // writes the count in Devanagari or Odia digits, and the browser's sentence and the
                // handset's would then differ for one and the same refusal.
                "This code is ${text.length} characters, and the largest symbol this app draws holds " +
                    "${capacity(MAX_VERSION, level)}.",
            )
        }

        var best: Array<BooleanArray>? = null
        var bestMask = 0
        // The web starts at POSITIVE_INFINITY; Int.MAX_VALUE is the same starting point for a score
        // that is a sum of small non-negative terms (a version 6 symbol scores under two thousand).
        var bestScore = Int.MAX_VALUE
        for (mask in 0 until 8) {
            val candidate = buildMatrix(text, version, level, mask)
            val score = penalty(candidate)
            // STRICTLY less than, so a tie keeps the LOWER mask number. `<=` would keep the higher
            // one, and the two clients would disagree about a symbol whose masks score equally —
            // which they do more often than the arithmetic suggests, because rule 1 and rule 2
            // dominate and are both coarse.
            if (score < bestScore) {
                bestScore = score
                best = candidate
                bestMask = mask
            }
        }

        return DwQrSymbol(
            // The loop always runs eight times and any score is below Int.MAX_VALUE, so this is
            // never null; checkNotNull says so out loud rather than asserting it with `!!`.
            matrix = checkNotNull(best) { "no mask was scored, which cannot happen" },
            size = 17 + 4 * version,
            version = version,
            level = level,
            mask = bestMask,
        )
    }

    /**
     * The dark modules of a symbol as one SVG path, in a coordinate space of 1 unit per module.
     *
     * ONE PATH, NOT ONE RECT PER MODULE. A version 4 symbol is 1089 modules; as `<rect>`s that is a
     * thousand nodes per card and a print sheet of thirty cards that a field device takes seconds to
     * lay out. It also renders more reliably: adjacent rects leave hairline seams at some zoom levels
     * in some renderers, and a seam across a QR module is exactly the artefact that makes a scanner
     * hesitate.
     *
     * [quiet] is included in the returned [DwQrSvg.extent] rather than left to the caller, because a
     * symbol printed hard against a card's border does not scan and there is no way to see that on
     * screen. Four modules is the standard's minimum.
     */
    fun svgPath(symbol: DwQrSymbol, quiet: Int = 4): DwQrSvg {
        val parts = StringBuilder()
        for (row in 0 until symbol.size) {
            var column = 0
            while (column < symbol.size) {
                if (!symbol.matrix[row][column]) {
                    column++
                    continue
                }
                // Runs are merged horizontally: a row of eight dark modules becomes one 8x1
                // rectangle rather than eight 1x1 ones, which roughly halves the path on a typical
                // symbol.
                var run = 1
                while (column + run < symbol.size && symbol.matrix[row][column + run]) run++
                // String template, never String.format — see the header. Every number in an SVG path
                // must be ASCII digits whatever the handset's locale is set to.
                parts.append("M").append(column + quiet).append(" ").append(row + quiet)
                    .append("h").append(run).append("v1h-").append(run).append("z")
                column += run
            }
        }
        return DwQrSvg(path = parts.toString(), extent = symbol.size + quiet * 2, symbol = symbol)
    }
}
