-- THE PRE-SUBMISSION LOOP'S STORE: four columns on "DesignWorkshop" and one new table.
--
-- Generated by hand and then checked against the model in schema.prisma -- the IF NOT EXISTS
-- clauses and the DO blocks below are not shapes `prisma migrate diff` emits, and they are here
-- because this deployment's migrations are applied by a runner that can be interrupted and re-run.
-- The same style as 20260830090000_usage_consent_and_decision_log.
--
-- ADDITIVE THROUGHOUT. Three nullable columns, one NOT NULL column whose DEFAULT means exactly what
-- every existing row already means ("never handed in"), one new table nothing has written to, five
-- new indexes and three new foreign keys. No column dropped, no column retyped, no constraint
-- relaxed, no existing index touched. Every row in the database plans and prints exactly as it did
-- yesterday.
--
-- IT NAMES NONE OF THE ENUM VALUES ADDED IN 20260913130000 OR 20260913130100, and that is a
-- requirement rather than a coincidence: Prisma wraps a migration in an implicit transaction and a
-- value added by ALTER TYPE cannot be USED in the same one. There is therefore no DEFAULT on a
-- status column here, no CHECK naming a token, no partial index and no backfill.
--
-- =============================================================================================
-- 1. WHY THE THREE COLUMNS ARE SPELLED reviewNotes / reviewedById / reviewedAt
-- =============================================================================================
--
-- Because six other tables in this database spell them that way -- "Artisan",
-- "ProductDocumentation", "ToolDocumentation", "Process", "QuestionnaireInterview", "MediaFile" --
-- and `app/services/records.py::review_update(status, notes, reviewer_id)` is the one function that
-- builds that dict. Reusing the spelling is what lets a workshop's decision be written by that
-- function rather than by a seventh hand-written copy of it that can drift from the other six. The
-- names are a contract with a function, and a rename here is a rename there.
--
-- =============================================================================================
-- 2. WHY "submissionRound" IS AN INTEGER AND NOT "DwReviewRound"
-- =============================================================================================
--
-- "DwReviewRound" is {PEER, POOL} and means an AUDIENCE: the people who were in the room, versus
-- every designer on the platform once `peerRoundClosedAt` is set on one sketch or prototype row. It
-- is per SUBJECT ROW and it is decided by a date, never by a workshop's status. A submission cycle
-- is a different quantity, and three clients already match exhaustively over those two tokens, so a
-- cycle number pushed in there breaks the web, the handset and the server at once.
--
-- DEFAULT 0 AND NO BACKFILL. Zero means "never handed in", which is true of every workshop in the
-- database on the day this lands, so the default asserts nothing that is not already the case.
--
-- =============================================================================================
-- 3. THE TWO CLOCKS ON "DwInspectionFeedback"
-- =============================================================================================
--
-- "recordedAt" is what the DEVICE said -- the moment the officer wrote the suggestion, which on
-- this fleet can be a fortnight before the server hears it -- and is NULL when the row was filed
-- straight against this server, where "createdAt" is the same moment and a copy would later read as
-- "a device reported this", which would be false. "createdAt" is always when the server heard it.
-- Collapsing them fabricates one of the two answers. Same pair, same rule, same reasoning as
-- "DwWorkshopConsentDecision" and "UsageConsentDecision".
--
-- =============================================================================================
-- 4. onDelete, ARGUED PER RELATION
-- =============================================================================================
--
-- "DesignWorkshop"."reviewedById" -> SET NULL. It is a CACHE of the latest decision; the record of
-- the ACT is the feedback row, whose actor is RESTRICT. An officer removed by hand leaves a
-- workshop that says "sent back, by somebody no longer on record" rather than a delete that fails
-- halfway or a report that silently stops being sent back.
--
-- "DwInspectionFeedback"."actorId" -> RESTRICT. This row says a named officer told a named designer
-- to change a ministry document. An account deleted out from under it would leave that instruction
-- attributed to nobody. Deleting such an account already fails on a dozen other relations and
-- `api/routes/users.py::_undeletable_detail` degrades honestly for the ones it cannot name.
--
-- "DwInspectionFeedback"."designWorkshopId" -> CASCADE. Nothing hard-deletes a workshop (DELETE
-- sets "deletedAt"), so this fires only on a deliberate database-level removal, and a suggestion
-- about a workshop that no longer exists is a statement about nothing.
--
-- =============================================================================================
-- 5. THE CHECK ON "round", AND THE WARNING THAT GOES WITH IT
-- =============================================================================================
--
-- `round >= 1`. A feedback row can only be written against a workshop that has been handed in at
-- least once -- the routes refuse a workshop whose status is not PRE_SUBMISSION or NEEDS_REVISION,
-- and both of those imply "submissionRound" >= 1 -- so a zero here means the copy from the workshop
-- row was skipped. The same shape as "DwReviewRating"'s score range: the rule is expressed where
-- Postgres can enforce it, not only where Python can.
--
-- ⚠ PRISMA HAS NO SYNTAX FOR A CHECK CONSTRAINT, so this one exists ONLY in this file. A
-- `prisma migrate dev` regeneration, a reset or a re-baseline reproduces the table WITHOUT it and
-- says nothing. `tests/test_design_workshop_review_loop.py::test_the_migration_matches_the_model`
-- reads this SQL off disk for exactly that reason.

-- AlterTable
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "reviewNotes" TEXT;
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "reviewedById" TEXT;
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "reviewedAt" TIMESTAMP(3);
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "submissionRound" INTEGER NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE IF NOT EXISTS "DwInspectionFeedback" (
    "id" TEXT NOT NULL,
    "designWorkshopId" TEXT NOT NULL,

    -- The submission cycle this suggestion is about, copied from
    -- "DesignWorkshop"."submissionRound" at write time. See section 2.
    "round" INTEGER NOT NULL,

    -- A `StageSpec.key`, validated against the Python registry before the write. NULL means "about
    -- the report as a whole", which is a real answer and not a missing one. A string and not a
    -- foreign key because the registry lives in Python and there is no stage table to point at.
    "stageKey" TEXT,

    -- A `FieldSpec.key` inside that stage. NOT validated: an officer legitimately names a field a
    -- client one release ahead is already showing, and refusing the row would lose the suggestion
    -- rather than the typo.
    "fieldKey" TEXT,

    -- WHAT TO CHANGE. NOT NULL and never blank: a send-back with no sentence is what
    -- `api/routes/review.py` already answers 422 to for the six record types.
    "note" TEXT NOT NULL,

    -- True when this row is the one that moved the workshop to NEEDS_REVISION.
    "sentBack" BOOLEAN NOT NULL DEFAULT false,

    "actorId" TEXT NOT NULL,

    -- TWO CLOCKS -- see section 3.
    "recordedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DwInspectionFeedback_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "DwInspectionFeedback_round_check" CHECK ("round" >= 1)
);

-- CreateIndex
-- One workshop's feedback in order: the read both detail routes make.
CREATE INDEX IF NOT EXISTS "DwInspectionFeedback_designWorkshopId_createdAt_idx"
    ON "DwInspectionFeedback"("designWorkshopId", "createdAt");

-- CreateIndex
-- One round's suggestions: what the designer's panel groups by and what a round selector on the
-- inspector's screen narrows to.
CREATE INDEX IF NOT EXISTS "DwInspectionFeedback_designWorkshopId_round_idx"
    ON "DwInspectionFeedback"("designWorkshopId", "round");

-- CreateIndex
-- The actor, indexed for the RESTRICT below rather than for a read: deleting a user makes Postgres
-- look for a row naming them, on every account deletion.
CREATE INDEX IF NOT EXISTS "DwInspectionFeedback_actorId_idx" ON "DwInspectionFeedback"("actorId");

-- CreateIndex
-- THE APPROVALS QUEUE READS `deletedAt IS NULL AND "submissionRound" > 0`, AND THAT IS THE WHOLE
-- PREDICATE. It carries no status term -- a queue narrowed by status could not show a report that
-- has been sent back -- so the composite is on the two columns the query actually names. An earlier
-- draft of this wave argued an index on ("status", "deletedAt") from a clause that does not mention
-- "status"; it is deliberately not created here.
CREATE INDEX IF NOT EXISTS "DesignWorkshop_deletedAt_submissionRound_idx"
    ON "DesignWorkshop"("deletedAt", "submissionRound");

-- CreateIndex
-- Indexed for the SET NULL it is on the wrong end of rather than for a read.
CREATE INDEX IF NOT EXISTS "DesignWorkshop_reviewedById_idx" ON "DesignWorkshop"("reviewedById");

-- AddForeignKey
DO $$
BEGIN
  -- SET NULL: a cache of the latest decision. See section 4.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'DesignWorkshop_reviewedById_fkey'
  ) THEN
    ALTER TABLE "DesignWorkshop" ADD CONSTRAINT "DesignWorkshop_reviewedById_fkey"
      FOREIGN KEY ("reviewedById") REFERENCES "User"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END
$$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'DwInspectionFeedback_designWorkshopId_fkey'
  ) THEN
    ALTER TABLE "DwInspectionFeedback" ADD CONSTRAINT "DwInspectionFeedback_designWorkshopId_fkey"
      FOREIGN KEY ("designWorkshopId") REFERENCES "DesignWorkshop"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END
$$;

-- AddForeignKey
DO $$
BEGIN
  -- RESTRICT: a named officer's instruction must outlive the account. See section 4.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'DwInspectionFeedback_actorId_fkey'
  ) THEN
    ALTER TABLE "DwInspectionFeedback" ADD CONSTRAINT "DwInspectionFeedback_actorId_fkey"
      FOREIGN KEY ("actorId") REFERENCES "User"("id")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END
$$;
