"""Regenerate `app/src/test/resources/dw-analysis-expected.json` from the BACKEND modules.

WHY THIS FILE EXISTS. `DwAnalysisParityTest` says of the golden it compares against: "It is
regenerated by running the case table through the backend modules." That sentence described a
procedure that lived in somebody's shell history and nowhere else — which is the same defect as a
comment asserting behaviour the code does not have, and worse here, because a golden nobody can
reproduce degrades from a measurement into a copy of whatever the Kotlin happened to print on the
day it was frozen. The whole claim the parity harness makes is that the frozen file is PYTHON'S
answer. This is how that stays checkable.

WHAT IT DOES NOT DO IS RUN THE KOTLIN. The two sides are deliberately run by different tools: this
writes what Python says, and `DwAnalysisParityTest` recomputes every case on the JVM and diffs it
leaf by leaf. If the two ever disagree, the Python is right and the Kotlin is broken — never the
other way round, and never "regenerate the golden until the test passes", which would turn the
harness into a machine for laundering a port's mistakes into expectations.

Run it from the repository root, which is where `backend/` is importable from:

    python android/tools/regenerate_dw_analysis_golden.py

Add `--check` to compare without writing — what a build machine that has a backend checkout should
run, and what proves the committed golden is still what today's Python produces:

    python android/tools/regenerate_dw_analysis_golden.py --check

WRITTEN WITH AN EXPLICIT UTF-8 ENCODING, and `ensure_ascii=False` so the Odia, the astral characters
and the rupee signs stay themselves. Redirecting Python's stdout on Windows dies on cp1252 the
moment it meets one of them — the same trap the registry regeneration carries a warning about in
`StageSchema.kt` — so this writes the file itself rather than printing it for a shell to capture.
"""

from __future__ import annotations

import argparse
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ANDROID = os.path.dirname(HERE)
REPO = os.path.dirname(ANDROID)

CASES = os.path.join(ANDROID, "app", "src", "test", "resources", "dw-analysis-cases.json")
GOLDEN = os.path.join(ANDROID, "app", "src", "test", "resources", "dw-analysis-expected.json")

sys.path.insert(0, os.path.join(REPO, "backend"))

try:
    from app.services import cost_integrity, market_analysis
except ModuleNotFoundError as problem:  # pragma: no cover - a checkout question, not a defect
    raise SystemExit(
        f"cannot import the backend services ({problem}). This script reads the Python it is "
        f"pinning, so it needs the backend checkout at {os.path.join(REPO, 'backend')}. The frozen "
        f"golden is what lets the Kotlin test run on a machine without one."
    )


def compute(table: dict) -> dict:
    """Every case in the table, keyed exactly as `DwAnalysisParityTest.computeAll` keys it.

    The three sections are called through the SAME public functions the Kotlin calls, in the same
    order, with the rows passed through untouched. Anything reshaped here would be a difference
    between the two sides that neither module is responsible for.
    """
    out: dict = {}

    for case in table["market"]:
        out["market/" + case["name"]] = market_analysis.market_findings_payload(
            market_analysis.analyse(
                responses=case["responses"],
                competitors=case["competitors"],
                bands=case["bands"],
                swot=case["swot"],
            )
        )

    # `position_competitors` is exercised on its own as well as through `analyse`, because the
    # category-matched / pooled fallback is chosen by a sample the whole-workshop path cannot be made
    # to hold on demand.
    for case in table["competitorPositions"]:
        observations = [
            market_analysis.PriceObservation(
                amount=float(entry["amount"]),
                category=entry["category"],
                source=entry["source"],
                group=entry["group"],
                label=entry["label"],
            )
            for entry in case["observations"]
        ]
        placed = market_analysis.position_competitors(case["competitors"], observations)
        out["competitorPositions/" + case["name"]] = [
            {
                "name": position.name,
                "seller": position.seller,
                "category": position.category,
                "price": position.price,
                "percentile": None if position.percentile is None else round(position.percentile, 4),
                "versusMedian": (
                    None if position.versus_median is None else round(position.versus_median, 2)
                ),
                "note": position.note,
            }
            for position in placed
        ]

    for case in table["cost"]:
        out["cost/" + case["name"]] = cost_integrity.cost_findings_payload(
            cost_integrity.analyse_cost_integrity(
                sheets=case["sheets"],
                material_lines=case["materialLines"],
                labour_lines=case["labourLines"],
                labels=case["labels"],
            )
        )

    return out


def serialise(payload: dict) -> str:
    # `sort_keys` so a re-run reorders nothing and a diff shows only what actually moved, and a
    # trailing newline so the file ends like a text file. The one-space indent is not a preference:
    # it is what the committed golden already uses, and a regeneration that reformatted all 4,109
    # lines would bury the two that actually changed under a whole-file diff nobody can review.
    return json.dumps(payload, ensure_ascii=False, sort_keys=True, indent=1) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare against the committed golden and exit non-zero if it has drifted",
    )
    arguments = parser.parse_args()

    with io.open(CASES, encoding="utf-8") as handle:
        table = json.load(handle)
    computed = compute(table)
    text = serialise(computed)

    if arguments.check:
        with io.open(GOLDEN, encoding="utf-8") as handle:
            existing = json.load(handle)
        if existing == computed:
            print(f"golden is current: {len(computed)} cases match today's Python")
            return 0
        # Named case by case. "The golden has drifted" is not something anybody can act on.
        drifted = sorted(
            key for key in set(existing) | set(computed)
            if existing.get(key) != computed.get(key)
        )
        print(f"GOLDEN HAS DRIFTED — {len(drifted)} case(s) differ from today's Python:")
        for key in drifted[:40]:
            print(f"  {key}")
        return 1

    with io.open(GOLDEN, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print(f"wrote {len(computed)} cases to {GOLDEN}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
