-- THE APPROVING AUTHORITY'S SIGN-OFF: eight columns on "DesignWorkshop", one on
-- "DwInspectionFeedback".
--
-- Generated by hand and then checked against the models in schema.prisma -- the IF NOT EXISTS
-- clauses and the DO blocks below are not shapes `prisma migrate diff` emits, and they are here
-- because this deployment's migrations are applied by a runner that can be interrupted and re-run.
-- The same style as 20260913130200_dw_inspection_feedback.
--
-- ADDITIVE THROUGHOUT. Eight nullable columns, one NOT NULL boolean whose DEFAULT means exactly what
-- every existing row already is ("an inspector wrote this"), three indexes, three foreign keys and
-- two CHECK constraints that every existing row satisfies. No column dropped, no column retyped, no
-- constraint relaxed, no existing index touched, no row rewritten. "ReviewLog" is not touched: the
-- decisions write rows of its existing shape.
--
-- NO ENUM IS TOUCHED. 'APPROVED' has been a member of "DesignWorkshopStatus" since 20260913130000,
-- a different transaction, so the CHECK below may name it here without the "unsafe use of new value
-- of enum type" failure that file's header describes.
--
-- =============================================================================================
-- 1. WHY COLUMNS AND NOT THE LOG ALONE
-- =============================================================================================
--
-- The review trio ("reviewNotes"/"reviewedById"/"reviewedAt", 20260913130200) is the cache of the
-- LAST decision of any kind and a hand-on overwrites it, while "approved by X on the 11th" has to
-- survive into SUBMITTED. "handedOnAt" is also the only thing that tells a SUBMITTED row the
-- approving authority handed on from one that carries the word's OLD meaning: 20260913130000
-- redefined SUBMITTED and deliberately backfilled nothing, so every SUBMITTED row in the database
-- today has "handedOnAt" NULL and keeps its old behaviour, and a handed-on one is frozen. And a list
-- reads the header without walking a log.
--
-- "approvedRound" is the "submissionRound" an approval was given in. "handedOnTo" is the office the
-- report was recorded as going to. "handedOnExportId" pins the exported file (a "DwReportExport"
-- row) the office received, when the authority chose one. "lastHandedInAt" is stamped on every entry
-- into PRE_SUBMISSION, and is what the approvals queue orders "waiting since" by -- "reviewedAt" is
-- cleared on that same entry and cannot.
--
-- NO BACKFILL, AND THE ABSENCE IS THE DECISION, for 20260913130000's reason: nobody approved or
-- handed on any existing row through this product, and a pointer saying somebody did would be a lie
-- in an audit trail. "lastHandedInAt" is NULL on every report handed in before today and the queue
-- orders those first, which is the right place for the oldest waits.
--
-- =============================================================================================
-- 2. "DwInspectionFeedback"."byApprovingAuthority"
-- =============================================================================================
--
-- The approving authority's sentences -- a report sent back without approval, an approval withdrawn,
-- a handed-on report returned -- go into the same register the designers already work through, round
-- by round, because each is a correction to make. They are not inspections: the ministry register's
-- per-inspector counts leave them out, and the screens label them. DEFAULT false is the truth about
-- every existing row, all of which an inspector wrote.
--
-- =============================================================================================
-- 3. THE TWO CHECKS, WHICH EXIST ONLY IN THIS FILE
-- =============================================================================================
--
-- Prisma has no syntax for a CHECK, so a `prisma migrate dev` regeneration would reproduce these
-- columns without them and say nothing; a test pins both, as it pins
-- "DwInspectionFeedback_round_check".
--
--   "DesignWorkshop_approved_has_approvedAt"   an APPROVED row says when it was approved. APPROVED has
--                                               been unreachable until today, so no existing row can
--                                               fail it.
--   "DesignWorkshop_handedOn_was_approved"      a row recorded as handed on was approved first.
--                                               Every existing row has "handedOnAt" NULL.
--
-- =============================================================================================
-- 4. onDelete
-- =============================================================================================
--
-- All three pointers are SET NULL, exactly as "reviewedById" is: the record of each act is a
-- "ReviewLog" row whose reviewer is RESTRICT, so a pointer going null loses a name on a cache and
-- never a record of responsibility. Each is indexed for the SET NULL it is on the wrong end of.

-- AlterTable
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "approvedById" TEXT;
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "approvedRound" INTEGER;
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "handedOnById" TEXT;
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "handedOnAt" TIMESTAMP(3);
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "handedOnTo" TEXT;
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "handedOnExportId" TEXT;
ALTER TABLE "DesignWorkshop" ADD COLUMN IF NOT EXISTS "lastHandedInAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "DwInspectionFeedback" ADD COLUMN IF NOT EXISTS "byApprovingAuthority" BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "DesignWorkshop_approvedById_idx" ON "DesignWorkshop"("approvedById");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "DesignWorkshop_handedOnById_idx" ON "DesignWorkshop"("handedOnById");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "DesignWorkshop_handedOnExportId_idx" ON "DesignWorkshop"("handedOnExportId");

-- AddForeignKey
DO $$
BEGIN
  -- SET NULL: a pointer; the act is the ReviewLog row. See section 4.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'DesignWorkshop_approvedById_fkey'
  ) THEN
    ALTER TABLE "DesignWorkshop" ADD CONSTRAINT "DesignWorkshop_approvedById_fkey"
      FOREIGN KEY ("approvedById") REFERENCES "User"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END
$$;

-- AddForeignKey
DO $$
BEGIN
  -- SET NULL: a pointer; the act is the ReviewLog row. See section 4.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'DesignWorkshop_handedOnById_fkey'
  ) THEN
    ALTER TABLE "DesignWorkshop" ADD CONSTRAINT "DesignWorkshop_handedOnById_fkey"
      FOREIGN KEY ("handedOnById") REFERENCES "User"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END
$$;

-- AddForeignKey
DO $$
BEGIN
  -- SET NULL: the hand-on must outlive an export row. See section 4.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'DesignWorkshop_handedOnExportId_fkey'
  ) THEN
    ALTER TABLE "DesignWorkshop" ADD CONSTRAINT "DesignWorkshop_handedOnExportId_fkey"
      FOREIGN KEY ("handedOnExportId") REFERENCES "DwReportExport"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END
$$;

-- AddCheckConstraint
DO $$
BEGIN
  -- An APPROVED row says when it was approved. See section 3.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'DesignWorkshop_approved_has_approvedAt'
  ) THEN
    ALTER TABLE "DesignWorkshop" ADD CONSTRAINT "DesignWorkshop_approved_has_approvedAt"
      CHECK ("status" <> 'APPROVED' OR "approvedAt" IS NOT NULL);
  END IF;
END
$$;

-- AddCheckConstraint
DO $$
BEGIN
  -- A row recorded as handed on was approved first. See section 3.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'DesignWorkshop_handedOn_was_approved'
  ) THEN
    ALTER TABLE "DesignWorkshop" ADD CONSTRAINT "DesignWorkshop_handedOn_was_approved"
      CHECK ("handedOnAt" IS NULL OR "approvedAt" IS NOT NULL);
  END IF;
END
$$;
