-- THE CONSENT FLOW THE PREVIOUS MIGRATION DELIBERATELY SHIPPED WITHOUT.
--
-- 20260829090000 created "UsageEvent" and said, in as many words: "CONSENT IS FLAGGED AND NOT
-- SETTLED ... `consentState` is a nullable place to RECORD an answer and NOT a flow that asks the
-- question." This is that flow's store. Two enum types, four columns on "User", and one new table.
--
-- Generated by hand rather than by `prisma migrate diff`, and then checked against a diff run --
-- see the IF NOT EXISTS notes and the two DO blocks below, neither of which `migrate diff` emits.
--
-- Additive throughout: two new types nothing referenced yesterday, four columns on "User" (three
-- nullable and one with a DEFAULT that means exactly what every existing row already means), one new
-- table nothing has written to. No column dropped, no column retyped, no constraint relaxed, no
-- existing index touched. Every row in the database plans and prints exactly as it did yesterday.
--
-- =============================================================================================
-- 1. WHY THE COLUMN IS NAMED "usageConsent" AND WHY THAT IS NOT A FREE CHOICE
-- =============================================================================================
--
-- `app/services/usage.py` has carried `CONSENT_ATTRIBUTE = "usageConsent"` since the table was
-- created, with a comment saying it is "the name this module will read off a `User` row once
-- somebody builds the flow ... named as a constant rather than inlined so the day the column lands
-- there is exactly one line to change and one grep to find it." `resolve_consent` reads it with
-- `getattr` off the `User` row the dependency layer has ALREADY loaded to authenticate the request,
-- which is what makes the whole consent lookup cost no extra round trip on the hot path.
--
-- THE FAILURE THAT NAMING BUYS PROTECTION FROM, stated so nobody renames it for tidiness: a
-- `getattr` miss does not raise. It returns None, `resolve_consent` reads that as NOT_RECORDED, and
-- collection for the ENTIRE FLEET silently reverts to anonymous with no error, no log line and no
-- test going red. The column name is a contract with a `getattr`, and `getattr` contracts fail
-- quietly.
--
-- =============================================================================================
-- 2. "UsageConsent" IS ITS OWN TYPE AND NOT "DwDictationConsent"
-- =============================================================================================
--
-- The three labels read identically and the FACT is different. `DwDictationConsent` is scoped to an
-- ARTISAN'S AUDIO leaving a device in a named workshop; this is a DESIGNER'S BROWSING of the
-- platform they work in. Reusing the type would file the two as one fact, after which the day either
-- meaning moves -- a fourth label, a rename, a tightening -- the other moves with it, decided by
-- somebody who was only thinking about one of them. "UsageEvent"."consentState" already refuses that
-- reuse in prose ("a designer's browsing consent and an artisan's recording consent must not be one
-- fact"); this makes the refusal structural.
--
-- =============================================================================================
-- 3. "UsageConsentBasis": THE COLUMN THAT KEEPS THE RECORD HONEST
-- =============================================================================================
--
-- The requirement is a blocking agreement at sign-in: refuse and you cannot use the product. That is
-- a CONDITION OF ACCESS, and under GDPR Art. 7(4) and the DPDP-style regimes this deployment sits
-- under, consent obtained that way is NOT FREELY GIVEN -- consent is not free where performance of
-- the service is made conditional on it and the processing is not necessary for the service.
--
-- The requirement is not refused. It is recorded truthfully. Storing GRANTED and nothing else would
-- record nine thousand turnstiles as nine thousand free choices, and no later reader -- a colleague,
-- an ethics board, a methods section -- could tell them apart. So the CIRCUMSTANCE is stored beside
-- the answer, on the "User" row and on every log row: REQUIRED_AT_SIGN_IN is the turnstile,
-- OFFERED_IN_SETTINGS is the free choice.
--
-- AND THE ASYMMETRY IS WHAT MAKES THE TURNSTILE DEFENSIBLE RATHER THAN MERELY DOCUMENTED. Every
-- WITHDRAWAL is an OFFERED_IN_SETTINGS decision, it costs the person nothing -- withdrawing does not
-- sign anybody out and does not remove any capability -- and it stops collection and DELETES what
-- was stored. A withdrawal that cost access would be theatre, and the whole flow would be
-- indefensible.
--
-- A FOURTH LABEL ON "UsageConsent" WAS THE OBVIOUS ALTERNATIVE AND IS REFUSED: it would break
-- `usage.collection_plan`'s three-way rule -- which is the whole of the collection policy, in one
-- function -- and the documented meaning of "UsageEvent"."consentState", in the same edit.
--
-- =============================================================================================
-- 4. "usageConsentVersion": SO A REWORD CANNOT CLAIM AGREEMENT TO WORDING NOBODY SAW
-- =============================================================================================
--
-- A consent record that cannot say WHAT WAS AGREED TO invites exactly the claim it cannot support:
-- that everybody on file agreed to whatever the notice says today. `usage.NOTICE_VERSION` mints the
-- token; `usage.consent_gate` compares it and asks again when it has moved.
--
-- IT IS STORED ON THE LOG ROW AS WELL AS ON "User" AND IS NOT DERIVABLE FROM THE DATE. A deployment
-- can be rolled back, two versions can be live at once behind a CDN, and a handset can hold a cached
-- notice for a fortnight. What the client says it showed is the only thing that answers the question
-- without a reader reconstructing a release timeline.
--
-- NOT NULL ON THE LOG, NULLABLE ON "User". A decision row always knows which text produced it, so
-- there is no honest NULL. The "User" column is NULL for every account that has not answered, which
-- is every account on the day this runs.
--
-- =============================================================================================
-- 5. THE DECISION LOG, AND WHY CASCADE HERE WHERE THE AUDIO LOG IS RESTRICT
-- =============================================================================================
--
-- The four columns on "User" are the current answer -- read by `resolve_consent` on a request a
-- designer is waiting on. The log is the history, and it is not optional: consent can be WITHDRAWN,
-- and a withdrawal would erase the answer the collection was made under. "Granted on the 3rd,
-- withdrawn on the 9th" is only answerable from a log. That is "DwWorkshopConsentDecision"'s
-- argument, transferred without alteration.
--
-- It matters MORE here, not less, because `usage.withdraw()` DELETES the stored "UsageEvent" rows.
-- After a withdrawal the observations are gone, and this log is then the only surviving evidence
-- that they were ever collected with an agreement behind them.
--
-- ON DELETE CASCADE, joining "UsageEvent" rather than "DwWorkshopConsentDecision", and the split is
-- deliberate. That log is RESTRICT because it records one person taking responsibility for ANOTHER
-- person's data -- deleting the actor would leave a record saying an artisan's recordings were
-- cleared for export by nobody. THIS log records a person's answer about THEMSELVES. When the
-- account goes, "UsageEvent" takes every observation with it, and a surviving consent row would be a
-- statement about data that no longer exists attached to a person who no longer exists -- while
-- adding one more permanently unclearable reason an admin cannot delete an account.
--
-- ONE INDEX, ("userId", "createdAt"): equality first, range last, which is the only order a btree
-- serves both halves of, and the same shape as "UsageEvent"'s two. It is also the index Postgres
-- probes for the CASCADE above, so an account deletion costs nothing beyond the delete.
--
-- =============================================================================================
-- 6. NO NEW INDEX ON "UsageEvent", AND THAT IS A DECISION RATHER THAN AN OMISSION
-- =============================================================================================
--
-- This wave also adds four aggregate read routes (/usage/timeline, /usage/latency, /usage/clients,
-- /usage/screens) and two trail routes. EVERY ONE OF THEM RIDES AN INDEX THAT ALREADY EXISTS:
-- the four aggregates are `"routeTemplate" IN (...) AND "createdAt" >= x AND < y`, which is a
-- bounded set of probes on ("routeTemplate", "createdAt"); both trail routes are `"userId" = $1` plus
-- the same range, which is ("userId", "createdAt").
--
-- There is still deliberately NO INDEX ON "createdAt" ALONE. It would be paid for on every insert
-- into what will be by far the highest-write table in this schema, to serve a whole-window scan
-- across every user and every route -- and no route added in this wave asks for one. A ranking over
-- EVERY screen discovered from the data is the query that would want it, which is why
-- /usage/screens ranks a NAMED, CAPPED set of templates and says so in its own response rather than
-- discovering the set from the table. If somebody later wants the global ranking, the answer is a
-- daily rollup table designed on purpose, not an index here.
--
-- =============================================================================================
-- 7. NO BACKFILL, AND THE NULLS ALREADY IN "UsageEvent"."consentState" ARE UNTOUCHED
-- =============================================================================================
--
-- "usageConsent" DEFAULTs to NOT_RECORDED, which is what every existing account genuinely is:
-- nobody has been asked. That is not a backfill inventing an answer -- it is the same statement the
-- absence of the column already made, now stored.
--
-- **NOTHING IN THIS FILE TOUCHES "UsageEvent"."consentState".** Every row written before today
-- carries NULL there, NULL means NOBODY WAS ASKED, and it is the only thing that keeps those rows
-- findable and deletable as a set. Backfilling them to "GRANTED" on the strength of a consent
-- collected afterwards would be this migration forging the one distinction the column exists for.
-- Whether those rows are DELETED on the day the flow ships is a decision for the owner, recorded as
-- an open item in docs/DECISION-usage-consent-at-sign-in.md.
--
-- =============================================================================================
-- WHY THIS IS SAFE TO APPLY, AND ROLLING BACK
-- =============================================================================================
--
-- IF NOT EXISTS / DO-block guards throughout, for 20260822120000's stated reason which still holds:
-- this lands in a wave where several agents apply migrations against one local Postgres, so a
-- half-applied run followed by a re-run is a realistic Tuesday. `CREATE TYPE` has no IF NOT EXISTS
-- in any supported Postgres, which is why the two types are wrapped in DO blocks that check
-- `pg_type` -- the same shape the FK guards below use against `pg_constraint`.
--
-- THERE IS NO DOWN-MIGRATION IN THIS PROJECT and pushing main deploys with no test gate, so the
-- rollback is hand-run and is worth stating in full:
--
--   DROP TABLE "UsageConsentDecision";
--   ALTER TABLE "User" DROP COLUMN "usageConsentVersion";
--   ALTER TABLE "User" DROP COLUMN "usageConsentBasis";
--   ALTER TABLE "User" DROP COLUMN "usageConsentAt";
--   ALTER TABLE "User" DROP COLUMN "usageConsent";
--   DROP TYPE "UsageConsentBasis";
--   DROP TYPE "UsageConsent";
--
-- In that order: the table references both types and the columns, so it goes first, and each type
-- has to outlive its last column. No "UsageEvent" row is touched by the rollback, because none is
-- touched by this file. What IS lost is every recorded answer -- so a rollback after the flow has
-- run in production silently returns the fleet to "nobody has been asked", which is the honest
-- reading of a database with no consent columns in it and is exactly why the drop order above ends
-- with the types rather than starting with them.

-- CreateEnum
-- Two DO blocks rather than two bare CREATE TYPEs: `CREATE TYPE ... IF NOT EXISTS` does not exist in
-- Postgres, and a bare CREATE TYPE on a re-run aborts the transaction and takes the rest of the file
-- with it.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'UsageConsent') THEN
    CREATE TYPE "UsageConsent" AS ENUM ('NOT_RECORDED', 'GRANTED', 'REFUSED');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'UsageConsentBasis') THEN
    CREATE TYPE "UsageConsentBasis" AS ENUM ('REQUIRED_AT_SIGN_IN', 'OFFERED_IN_SETTINGS');
  END IF;
END
$$;

-- AlterTable
-- The DEFAULT is NOT_RECORDED and it is not a backfill: it stores the statement the absence of the
-- column was already making. The three that follow are nullable because "nobody has answered" has no
-- moment, no circumstance and no version -- and a DEFAULT on any of them would put a fabricated fact
-- on every row in the table.
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "usageConsent" "UsageConsent" NOT NULL DEFAULT 'NOT_RECORDED';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "usageConsentAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "usageConsentBasis" "UsageConsentBasis";
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "usageConsentVersion" TEXT;

-- CreateTable
CREATE TABLE IF NOT EXISTS "UsageConsentDecision" (
    "id" TEXT NOT NULL,

    -- THE SUBJECT AND THE ACTOR ARE THE SAME ACCOUNT, which is the one structural difference from
    -- "DwWorkshopConsentDecision". There a designer records an ARTISAN'S answer, so the row carries
    -- an `actorId` naming somebody other than the subject. Here the person answering is the person
    -- being observed, so there is one column and no responsibility taken on anybody else's behalf.
    -- There is deliberately no route by which an administrator records a colleague's usage consent:
    -- a consent an admin can enter for somebody else is not a consent.
    "userId" TEXT NOT NULL,

    -- GRANTED or REFUSED. NOT_RECORDED is refused as a DECISION in `usage.consent_decision_plan`:
    -- it is the absence of an answer, and "somebody deliberately recorded that nobody has been
    -- asked" is not a state a person can be in. REFUSED is how a consent is withdrawn.
    "decision" "UsageConsent" NOT NULL,

    -- The turnstile or the free choice -- see section 3. On EVERY row and not only on the "User"
    -- cache, so a history read can tell which of a person's answers were freely given.
    "basis" "UsageConsentBasis" NOT NULL,

    -- NOT NULL: a decision row always knows which text produced it, so there is no honest NULL here.
    -- See section 4 for why it is stored rather than derived from the date.
    "noticeVersion" TEXT NOT NULL,

    "note" TEXT,

    -- TWO CLOCKS. "recordedAt" is what the CLIENT said -- when the box was ticked -- and is NULL when
    -- the answer was taken straight against this server, where "createdAt" is the same moment and a
    -- copy would later read as "a device reported this", which would be false. "createdAt" is always
    -- when the server heard it. Android signs people in offline-capable contexts and syncs later, so
    -- the two can differ by a fortnight; collapsing them fabricates one of the two answers -- a
    -- signature dated to the day it was filed.
    "recordedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UsageConsentDecision_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
-- One account's answers in order: the only read this table has, and the index Postgres probes for
-- the CASCADE below.
CREATE INDEX IF NOT EXISTS "UsageConsentDecision_userId_createdAt_idx" ON "UsageConsentDecision"("userId", "createdAt");

-- AddForeignKey
DO $$
BEGIN
  -- CASCADE, joining "UsageEvent" rather than the decision ledgers -- see section 5. When the account
  -- goes, its observations go with it, and a consent row about deleted data would be a statement
  -- about nothing attached to nobody.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'UsageConsentDecision_userId_fkey'
  ) THEN
    ALTER TABLE "UsageConsentDecision" ADD CONSTRAINT "UsageConsentDecision_userId_fkey"
      FOREIGN KEY ("userId") REFERENCES "User"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END
$$;
