"""Reference QR matrices for `frontend/e2e/workshop-codes.spec.ts`, from a SECOND encoder.

    backend/.venv/Scripts/python.exe scripts/qr_oracle.py > frontend/e2e/fixtures/qr-reference.json

`frontend/lib/qrEncode.ts` is a hand-written QR encoder — see that file's header for why it is not
a dependency — and a hand-written encoder checked only against itself is checked against nothing.
So the fixture is generated by ``reportlab.graphics.barcode.qrencoder``, which is already in
``backend/.venv`` for the report writer: a different implementation, in a different language, by
different people, from the same ISO 18004.

ALL EIGHT MASKS ARE DUMPED PER CASE, and mask SELECTION is deliberately NOT compared. reportlab's
penalty scorer has two departures from the standard — its vertical rule-3 pass compares a tuple
against a list and therefore never fires, and it looks only for the dark-first finder-lookalike,
not the mirrored one — so the two implementations may legitimately prefer different masks. Every
mask produces a legal, scannable symbol; what the comparison pins down is everything that decides
whether it is *readable*: mode, character count, padding, Reed-Solomon, block interleaving, the
function patterns, data placement, the mask patterns themselves and the format information.

The check characters are recomputed here rather than imported, for the same reason: a payload
whose check this script and `lib/workshopCodes.ts` agree on is a payload two independent
implementations of FNV-1a agree on, which is what a future Kotlin port has to match as well.
"""
import json
import sys

from reportlab.graphics.barcode import qrencoder

# Crockford base32 — no I, L, O or U. Keep in step with CHECK_ALPHABET in lib/workshopCodes.ts.
CHECK_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


def check_chars(prefix: str) -> str:
    """FNV-1a over the prefix; the low 20 bits as four base32 characters, most significant first."""
    h = 0x811C9DC5
    for byte in prefix.encode("ascii"):
        h ^= byte
        h = (h * 0x01000193) & 0xFFFFFFFF
    v = h & 0xFFFFF
    return "".join(CHECK_ALPHABET[(v >> shift) & 31] for shift in (15, 10, 5, 0))


def payload(record_type: str, record_id: str) -> str:
    prefix = f"DPW1:{record_type}:{record_id.upper()}"
    return f"{prefix}:{check_chars(prefix)}"


# reportlab's own constants, which are the two-bit format values and NOT an L→H ordering.
LEVELS = {"L": 1, "M": 0, "Q": 3, "H": 2}

CASES = [
    # The standard's own worked example, so a total misreading of the mode encoding shows up in the
    # one string every QR reference in print agrees about.
    ("HELLO WORLD", 1, "Q"),
    # A real artisan card: a 25-character cuid at level Q, which is what the sheet prints.
    (payload("A", "cmsik2jg8000eh8xc1lcy661a"), 3, "Q"),
    (payload("P", "cmt0prototype0001abc"), 3, "Q"),
    # A prototype tag printed before the row ever synced, identified by its 36-character UUID
    # client key. This is the largest symbol the app produces in practice.
    (payload("A", "3f7a91c2-0b4d-4e19-9c2a-1d5e6f708a9b"), 4, "Q"),
    # The other three error-correction levels, and a version whose blocks are cut differently.
    ("DPW1:P:ABCDEFGH:0000", 1, "M"),
    ("DPW1:P:ABCDEFGH:0000", 2, "H"),
    (payload("A", "cmsik2jg8000eh8xc1lcy661a") + ":" + "X" * 120, 6, "L"),
]

# The alphanumeric capacities `qrCapacity` derives from its block table. Asserted here so that the
# fixture cannot be regenerated against a version the TypeScript would not have chosen.
CAPACITY = {
    (1, "L"): 25, (1, "M"): 20, (1, "Q"): 16, (1, "H"): 10,
    (2, "L"): 47, (2, "M"): 38, (2, "Q"): 29, (2, "H"): 20,
    (3, "L"): 77, (3, "M"): 61, (3, "Q"): 47, (3, "H"): 35,
    (4, "L"): 114, (4, "M"): 90, (4, "Q"): 67, (4, "H"): 50,
    (5, "L"): 154, (5, "M"): 122, (5, "Q"): 87, (5, "H"): 64,
    (6, "L"): 195, (6, "M"): 154, (6, "Q"): 108, (6, "H"): 84,
}

for text, version, level in CASES:
    assert len(text) <= CAPACITY[(version, level)], ("does not fit", text, version, level)
    if version > 1:
        assert len(text) > CAPACITY[(version - 1, level)], ("not the smallest that fits", text, version, level)

out = []
for text, version, level in CASES:
    masks = []
    for mask in range(8):
        qr = qrencoder.QRCode(version, LEVELS[level])
        qr.addData(text)
        # makeImpl rather than make: make() picks its own mask, and the point here is to pin all
        # eight. `False` is "not a scoring pass", which is what writes the real format information.
        qr.makeImpl(False, mask)
        n = qr.getModuleCount()
        masks.append("/".join("".join("1" if qr.isDark(r, c) else "0" for c in range(n)) for r in range(n)))
    out.append({"text": text, "version": version, "level": level, "masks": masks})

json.dump(out, sys.stdout)
