import { readFileSync } from "node:fs";
import { join } from "node:path";

import { expect, test } from "@playwright/test";

import { photograph, type Quad } from "./support/qrPhotograph";

import { decodeQrFromGrey, decodeQrMatrix } from "@/lib/qrDecode";
import { buildQrMatrix, encodeQr, qrCapacity, type QrEccLevel } from "@/lib/qrEncode";
import { encodeWorkshopCode, decodeWorkshopCode } from "@/lib/workshopCodes";

/**
 * Unit tests for lib/qrDecode.ts — reading a QR symbol out of a photograph.
 *
 * WHAT THESE EXIST TO CATCH, in one sentence each, because a decoder has two completely different
 * ways of being wrong and only one of them looks like a failure:
 *
 *   - **It refuses a code it should read.** Annoying, visible, and the designer types the code
 *     instead. Every "decodes" test below is against this.
 *   - **It reads a code as the WRONG STRING.** Silent, and catastrophic in this application: a
 *     scanned identifier that is one character out is a different record or no record, and nothing
 *     downstream can tell. Every assertion here is therefore on the exact decoded TEXT, never on
 *     `result.ok` — `expect(result.ok).toBe(true)` passes for a decoder that returns the empty
 *     string, and would have passed for three of the defects found while writing this file.
 *
 * WHY THE REFERENCE SYMBOLS COME FROM REPORTLAB AND NOT FROM OUR OWN ENCODER. A decoder checked
 * only against the encoder beside it is checked against a mirror: any shared misreading of ISO
 * 18004 cancels exactly and the round trip passes while every real symbol fails. `qr-decode-
 * reference.json` is generated by `scripts/qr_decode_oracle.py` from reportlab — a different
 * implementation, in a different language — and it carries the two segment modes our own encoder
 * cannot even produce (byte and numeric), which are the modes every FOREIGN code arrives in.
 *
 * THE ROUND TRIP IS KEPT AS WELL, and it is not redundant: it is the only thing that covers every
 * version and level combination the application actually prints, and it is what would catch the
 * two files drifting apart after a change to the shared tables in `qrEncode.ts`.
 *
 * WHY THE PHOTOGRAPHS ARE SYNTHETIC — the same argument `e2e/sketch-rectify.spec.ts` and
 * `e2e/photo-measure.spec.ts` make. Every image below is CONSTRUCTED from its answer: a known
 * matrix, warped by a homography written down in advance, lit by a gradient chosen in advance, with
 * a glare blob of a chosen radius in a chosen place. "It still decoded" is then a statement about
 * the decoder. A test against a real photograph could only assert that the module still returns
 * whatever it returned the day it was written, and could never be made harder on purpose.
 */

/* ────────────────────────────────────────────────────────────────────────────
 * Reading symbols a different implementation drew
 * ──────────────────────────────────────────────────────────────────────────── */

type ReferenceCase = { text: string; version: number; level: QrEccLevel; why: string; masks: string[] };

const referenceCases = JSON.parse(
  readFileSync(join(__dirname, "fixtures", "qr-decode-reference.json"), "utf-8")
) as ReferenceCase[];

function matrixFromRows(rows: string): boolean[][] {
  return rows.split("/").map((row) => row.split("").map((cell) => cell === "1"));
}

test("every mask of every reference symbol from an independent encoder decodes to its exact text", () => {
  expect(referenceCases.length).toBeGreaterThan(5);
  const wrong: string[] = [];

  for (const entry of referenceCases) {
    for (let mask = 0; mask < 8; mask++) {
      const result = decodeQrMatrix(matrixFromRows(entry.masks[mask]));
      if (!result.ok) {
        wrong.push(`v${entry.version}${entry.level} mask ${mask} (${entry.why}): refused — ${result.reason}`);
        continue;
      }
      if (result.text !== entry.text) {
        wrong.push(`v${entry.version}${entry.level} mask ${mask} (${entry.why}): read "${result.text}"`);
        continue;
      }
      // The declared level and mask are read out of the symbol's own format strip, so getting the
      // text right while reporting the wrong mask would mean the unmasking happened to cancel —
      // possible for one symbol, and a defect that would surface on the next one.
      if (result.mask !== mask || result.level !== entry.level || result.version !== entry.version) {
        wrong.push(`v${entry.version}${entry.level} mask ${mask}: reported v${result.version}${result.level} mask ${result.mask}`);
      }
    }
  }

  expect(wrong).toEqual([]);
});

test("the segment modes our own encoder cannot produce are read — byte and numeric", () => {
  // Stated as its own test because it is the coverage that would otherwise be invisible: `qrEncode`
  // is alphanumeric-only by design, so without the reportlab fixture these two parsers would never
  // run at all, and a foreign QR would be reported as "no code found" rather than refused honestly.
  const byte = referenceCases.find((entry) => entry.text === "https://example.org/artisans/abc");
  expect(byte, "the byte-mode URL case is missing from the fixture").toBeTruthy();
  const decodedByte = decodeQrMatrix(matrixFromRows((byte as ReferenceCase).masks[0]));
  expect(decodedByte.ok && decodedByte.text).toBe("https://example.org/artisans/abc");

  const numeric = referenceCases.find((entry) => entry.text === "0123456789012345");
  expect(numeric, "the numeric case is missing from the fixture").toBeTruthy();
  const decodedNumeric = decodeQrMatrix(matrixFromRows((numeric as ReferenceCase).masks[3]));
  expect(decodedNumeric.ok && decodedNumeric.text).toBe("0123456789012345");
});

test("a decoded foreign code reaches the payload grammar and is refused as not ours, not as damaged", () => {
  // THE POINT OF DECODING SOMETHING THAT IS NOT OURS. The two refusals lead to different actions:
  // "that is not a workshop card" means stop, and "the tag is damaged" means photograph it again.
  // A decoder that could not read byte mode would produce the second for every payment QR on earth.
  const url = referenceCases.find((entry) => entry.text === "https://example.org/artisans/abc") as ReferenceCase;
  const decoded = decodeQrMatrix(matrixFromRows(url.masks[5]));
  expect(decoded.ok).toBe(true);
  if (!decoded.ok) return;
  const grammar = decodeWorkshopCode(decoded.text);
  expect(grammar).toMatchObject({ ok: false, reason: "NOT_A_WORKSHOP_CODE" });
});

/* ────────────────────────────────────────────────────────────────────────────
 * The round trip, over everything the application prints
 * ──────────────────────────────────────────────────────────────────────────── */

const ARTISAN_ID = "cmsik2jg8000eh8xc1lcy661a";
/** What a prototype row is known by before it has ever reached the server — the longest payload. */
const CLIENT_KEY = "3f7a91c2-0b4d-4e19-9c2a-1d5e6f708a9b";

test("every version and level this app can draw round-trips to the exact same string", () => {
  const wrong: string[] = [];
  for (const level of ["L", "M", "Q", "H"] as QrEccLevel[]) {
    for (let version = 1; version <= 6; version++) {
      // Filled to the version's capacity, so the padding, the terminator and — at the top end —
      // the multi-block interleaving are all exercised rather than only the first few codewords.
      const capacity = qrCapacity(version, level);
      const text = "DPW1:P:ABCDEFGH:0000".slice(0, Math.min(20, capacity)).padEnd(capacity, "X");
      for (let mask = 0; mask < 8; mask++) {
        const result = decodeQrMatrix(buildQrMatrix(text, version, level, mask));
        if (!result.ok) wrong.push(`v${version}${level} mask ${mask}: refused — ${result.reason}`);
        else if (result.text !== text) wrong.push(`v${version}${level} mask ${mask}: read "${result.text}"`);
      }
    }
  }
  expect(wrong).toEqual([]);
});

test("a real artisan card and an unsynced prototype tag both come back as the record they name", () => {
  for (const [recordType, id] of [
    ["artisan", ARTISAN_ID],
    ["prototype", CLIENT_KEY]
  ] as const) {
    const encoded = encodeWorkshopCode({ recordType, id });
    expect(encoded.ok).toBe(true);
    if (!encoded.ok) return;

    const decoded = decodeQrMatrix(encodeQr(encoded.code, "Q").matrix);
    expect(decoded.ok && decoded.text).toBe(encoded.code);
    // All the way through the grammar, because that is the journey a scan actually makes: a
    // decoder that dropped the check characters would still "decode" and would then be refused.
    expect(decoded.ok && decodeWorkshopCode(decoded.text)).toMatchObject({ ok: true, ref: { recordType, id } });
  }
});

/* ────────────────────────────────────────────────────────────────────────────
 * Damage — the reason error correction is in the file at all
 * ──────────────────────────────────────────────────────────────────────────── */

test("a symbol damaged within its error-correction budget still yields the exact identifier", () => {
  // WHAT THIS PINS. Cards printed by this app are level Q — a quarter of every block recoverable —
  // and they spend a fortnight in a workshop collecting thumbprints, dye and a fold across one
  // corner. Without a working Reed-Solomon decoder the upload path reads pristine screenshots and
  // nothing that has ever been in a workshop, which is the opposite of the case it exists for.
  const encoded = encodeWorkshopCode({ recordType: "artisan", id: ARTISAN_ID });
  expect(encoded.ok).toBe(true);
  if (!encoded.ok) return;

  const symbol = encodeQr(encoded.code, "Q");
  const damaged = symbol.matrix.map((row) => [...row]);

  // A contiguous smear, not scattered noise: that is the shape real damage has, and it is the
  // shape the encoder's block INTERLEAVING exists to survive — the smear lands a little on every
  // block instead of destroying one outright. Six rows of eight modules in the lower middle, well
  // clear of the finder patterns and the format strips, which carry no data and are not repairable.
  for (let row = 14; row < 20; row++) {
    for (let column = 12; column < 20; column++) damaged[row][column] = !damaged[row][column];
  }

  const result = decodeQrMatrix(damaged);
  expect(result.ok && result.text).toBe(encoded.code);
});

test("a symbol damaged BEYOND its budget is refused, and never guesses at an identifier", () => {
  // THE MORE IMPORTANT HALF OF THE PREVIOUS TEST. Berlekamp-Massey and Forney will happily produce
  // a "correction" for a block that is past saving; what stops that becoming a confident wrong
  // record is the syndrome recomputation at the foot of `correctBlock`. Deleting that check leaves
  // the test above passing and this one failing, which is exactly the guard rail wanted.
  const encoded = encodeWorkshopCode({ recordType: "artisan", id: ARTISAN_ID });
  if (!encoded.ok) return;
  const symbol = encodeQr(encoded.code, "Q");
  const wrecked = symbol.matrix.map((row) => [...row]);

  for (let row = 9; row < 26; row++) {
    for (let column = 9; column < 26; column++) wrecked[row][column] = (row * 7 + column * 3) % 2 === 0;
  }

  const result = decodeQrMatrix(wrecked);
  // The one thing that must never happen is a DIFFERENT valid-looking code coming back.
  if (result.ok) expect(result.text).toBe(encoded.code);
  else expect(["DATA_UNRECOVERABLE", "UNREADABLE"]).toContain(result.reason);
});

test("a symbol larger than this app prints is named as foreign, not reported as damaged", () => {
  // Version 7 — one past the ceiling `qrEncode.ts` draws and `qrDecode.ts` reads. A designer who
  // points this at a shipping label must be told to stop, not told to take a better photograph.
  const size = 17 + 4 * 7;
  const blank = Array.from({ length: size }, () => new Array<boolean>(size).fill(false));
  const result = decodeQrMatrix(blank);
  expect(result.ok).toBe(false);
  if (result.ok) return;
  expect(result.reason).toBe("UNSUPPORTED_VERSION");
  expect(result.message).toMatch(/not one of ours|bigger than any card/i);
});

/* ────────────────────────────────────────────────────────────────────────────
 * Photographs: skew, glare, and a code that is a small part of a large picture
 * ──────────────────────────────────────────────────────────────────────────── */

/*
 * The photograph simulator lives in `e2e/support/qrPhotograph.ts` rather than here, because
 * `workshop-codes-ui.spec.ts` drives the real upload control with a PNG built from the same planes.
 * Two copies of it is how one spec comes to be quietly easier than the other — and the easier one
 * would be the UI test, which is the one asserting that a designer in a courtyard can upload a
 * photograph at all. See that module for why the images are constructed rather than checked in.
 */

function cardCode(): string {
  const encoded = encodeWorkshopCode({ recordType: "artisan", id: ARTISAN_ID });
  if (!encoded.ok) throw new Error("the fixture payload no longer encodes");
  return encoded.code;
}

test("a photograph taken straight on decodes to the exact code", () => {
  const code = cardCode();
  const symbol = encodeQr(code, "Q");
  const plane = photograph(symbol.matrix, 520, 400, [
    { x: 120, y: 60 },
    { x: 400, y: 60 },
    { x: 400, y: 340 },
    { x: 120, y: 340 }
  ]);

  const result = decodeQrFromGrey(plane);
  expect(result.ok && result.text).toBe(code);
});

test("a card photographed AT AN ANGLE decodes — the alignment pattern earning its place", () => {
  // THE CASE THREE POINTS CANNOT SOLVE. A perspective view is not an affine one: parallel edges
  // converge, and a grid laid down from the three finder patterns alone drifts further wrong the
  // further it gets from them, until the far corner is sampling the neighbouring module. The
  // alignment pattern is the fourth point that pins that corner. Delete `findAlignment`'s call in
  // `decodeQrFromGrey` and this test is the one that goes red.
  const code = cardCode();
  const symbol = encodeQr(code, "Q");
  const plane = photograph(symbol.matrix, 640, 480, [
    { x: 96, y: 74 },
    { x: 505, y: 128 },
    { x: 470, y: 430 },
    { x: 132, y: 372 }
  ]);

  const result = decodeQrFromGrey(plane);
  expect(result.ok && result.text).toBe(code);
});

/** The skewed quad both screen-photograph cases below use, so the only variable between them is the glare. */
const SCREEN_QUAD: Quad = [
  { x: 150, y: 92 },
  { x: 560, y: 128 },
  { x: 534, y: 452 },
  { x: 176, y: 404 }
];

test("a photograph of a SCREEN — skewed, lit from one side, with glare burnt across its data — decodes", () => {
  // THE CASE THE UPLOAD PATH EXISTS FOR, and the one a camera scan usually cannot get: somebody has
  // photographed a code off a laptop screen and sent it on. The lamp gradient is what a local
  // threshold is for; the glare is a saturated hole in the DATA, which no threshold can recover and
  // only the error correction can. Both at once, on a skewed quad, is the honest version of the
  // claim in `qrDecode.ts`'s header.
  //
  // WHY THE GLARE IS AT (350, 270) AND NOT AT (470, 190), WHERE THIS TEST USED TO PUT IT. (470, 190)
  // is 8px from the TOP-RIGHT FINDER PATTERN's own centre, and the blob saturates everything within
  // about 20px of itself to pure white — so that version of this test burnt away a whole finder
  // pattern and then asserted the symbol still read. Nothing can pass it. A finder pattern is not
  // data: it carries no error-correction codewords, it is the thing the detector locates the symbol
  // BY, and two finders do not determine a symbol's position, size or orientation. The assertion was
  // not a hard bar, it was an impossible one, and it sat red while it was read as evidence that the
  // decoder could not cope with glare.
  //
  // (350, 270) is in the middle of the data area — at least 130px from every finder and from the
  // alignment pattern — so the glare now destroys exactly what the comment says it destroys, and
  // level H's error correction is what brings the code back. The case that USED to be tested here,
  // glare over a finder, is now tested one test down for the refusal it must produce instead.
  const code = cardCode();
  const symbol = encodeQr(code, "H");
  const plane = photograph(symbol.matrix, 700, 520, SCREEN_QUAD, {
    gradient: true,
    glare: { x: 350, y: 270, radius: 52 }
  });

  const result = decodeQrFromGrey(plane);
  expect(result.ok && result.text).toBe(code);
});

test("glare that burns away a FINDER pattern is refused with advice, not read as a wrong code", () => {
  // THE OTHER HALF OF THE TEST ABOVE, and the more important half for the person holding the phone.
  // A specular highlight sitting on a corner of the symbol is an ordinary way to photograph a screen,
  // and when it lands on a finder pattern the symbol genuinely cannot be located — three finders are
  // what fix its position, scale and orientation, and they have no error correction behind them.
  //
  // What must NOT happen is the decoder assembling a trio out of two real finders and something else
  // in the picture and reading a confident wrong string. This asserts the refusal, and asserts that
  // the sentence tells somebody what to do differently — moving the light, or tilting the screen, is
  // the fix, and a message saying only "could not read" sends them to photograph it the same way
  // again.
  const code = cardCode();
  const symbol = encodeQr(code, "H");
  const plane = photograph(symbol.matrix, 700, 520, SCREEN_QUAD, {
    gradient: true,
    glare: { x: 470, y: 190, radius: 52 }
  });

  const result = decodeQrFromGrey(plane);
  // A read would mean the decoder invented a symbol from two finders and a coincidence.
  expect(result.ok).toBe(false);
  if (result.ok) return;
  expect(result.reason).toBe("NO_SYMBOL");
  expect(result.message).toMatch(/frame|focus|crop|corner/i);
});

test("a code occupying a small corner of a large photograph is found and read", () => {
  // "The whole square is in the frame" is advice, not a requirement: a designer photographs a card
  // on a table from standing height and the code is a twentieth of the picture. The symbol here is
  // 190px across in a 1400x1000 frame — under 3% of its area.
  const code = cardCode();
  const symbol = encodeQr(code, "Q");
  const plane = photograph(symbol.matrix, 1400, 1000, [
    { x: 980, y: 690 },
    { x: 1170, y: 700 },
    { x: 1166, y: 886 },
    { x: 978, y: 878 }
  ]);

  const result = decodeQrFromGrey(plane);
  expect(result.ok && result.text).toBe(code);
});

test("a code photographed upside down, and one photographed mirrored, both decode", () => {
  const code = cardCode();
  const symbol = encodeQr(code, "Q");

  // Rotating the QUAD rather than the pixels: giving the corners in a different rotation is
  // precisely what holding the card the other way up does, and it exercises the detector's
  // orientation logic rather than a helper that flips an array.
  const upsideDown = photograph(symbol.matrix, 520, 400, [
    { x: 400, y: 340 },
    { x: 120, y: 340 },
    { x: 120, y: 60 },
    { x: 400, y: 60 }
  ]);
  expect(decodeQrFromGrey(upsideDown).ok && (decodeQrFromGrey(upsideDown) as { text: string }).text).toBe(code);

  // A MIRRORED picture — a front camera in mirror mode, or a code reflected in a window. Handled by
  // the transpose retry in `decodeQrFromGrey`; without it this is an "unreadable" for a symbol that
  // is perfectly intact.
  const mirrored = photograph(symbol.matrix, 520, 400, [
    { x: 400, y: 60 },
    { x: 120, y: 60 },
    { x: 120, y: 340 },
    { x: 400, y: 340 }
  ]);
  const result = decodeQrFromGrey(mirrored);
  expect(result.ok && result.text).toBe(code);
});

/* ────────────────────────────────────────────────────────────────────────────
 * Honest refusals — a file that is not a QR must say so, and say what to do
 * ──────────────────────────────────────────────────────────────────────────── */

test("a picture with no QR code in it is refused with a sentence that names the next action", () => {
  // A photograph of a loom, a page of notes, a blank wall: the commonest wrong file by far, and a
  // silent no-op here is the worst possible outcome — the designer presses Upload again with the
  // same file, then decides the feature is broken.
  const width = 480;
  const height = 360;
  const data = new Uint8ClampedArray(width * height);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      // Structure, not flat grey: diagonal banding and a soft blob, so this is a real negative and
      // not a picture with nothing in it for the detector to consider.
      const bands = 120 + 90 * Math.sin((x + y) / 9);
      const blob = 40 * Math.exp(-(((x - 300) ** 2 + (y - 120) ** 2) / 3600));
      data[y * width + x] = bands + blob;
    }
  }

  const result = decodeQrFromGrey({ data, width, height });
  expect(result.ok).toBe(false);
  if (result.ok) return;
  expect(result.reason).toBe("NO_SYMBOL");
  // The sentence has to tell somebody what to do differently. "Could not read the image" does not.
  expect(result.message).toMatch(/frame|focus|crop/i);
  expect(result.message.length).toBeGreaterThan(40);
});

test("an image too small to hold a symbol is refused as too small, not as containing no code", () => {
  const data = new Uint8ClampedArray(12 * 12).fill(200);
  const result = decodeQrFromGrey({ data, width: 12, height: 12 });
  expect(result.ok).toBe(false);
  if (result.ok) return;
  expect(result.message).toMatch(/too small/i);
});

test("a located but unreadable symbol reports WHERE it was, so a bigger copy can be cut out", () => {
  // The region is the mechanism behind reading a code that is a small part of a large photograph:
  // `lib/qrImageDecode.ts` finds the symbol in a cheap downscaled copy and re-cuts that rectangle
  // out of the full-resolution original. A refusal that dropped the region would leave that whole
  // second attempt with nowhere to look.
  const code = cardCode();
  const symbol = encodeQr(code, "Q");
  const quad: Quad = [
    { x: 700, y: 500 },
    { x: 860, y: 500 },
    { x: 860, y: 660 },
    { x: 700, y: 660 }
  ];
  const plane = photograph(symbol.matrix, 1200, 900, quad);
  // Destroy the payload while leaving the finder patterns and the geometry intact, which is what a
  // symbol too coarsely sampled to read actually looks like to the detector.
  for (let y = 545; y < 615; y++) {
    for (let x = 745; x < 815; x++) plane.data[y * plane.width + x] = (x * 5 + y * 3) % 2 === 0 ? 20 : 235;
  }

  const result = decodeQrFromGrey(plane);
  if (result.ok) return; // Recovered anyway — a stronger outcome than the one under test.
  expect(result.region, "a located symbol must report its region").toBeTruthy();
  const region = result.region as { x: number; y: number; width: number; height: number };
  // The rectangle has to actually contain the symbol, in fractions of the frame.
  expect(region.x).toBeLessThan(700 / 1200);
  expect(region.x + region.width).toBeGreaterThan(860 / 1200);
  expect(region.y).toBeLessThan(500 / 900);
  expect(region.y + region.height).toBeGreaterThan(660 / 900);
});
