/**
 * A QR symbol, drawn in this browser, from nothing but this file.
 *
 * WHY THIS IS HAND-WRITTEN AND NOT A DEPENDENCY. The codes this encodes are printed on artisan
 * cards and prototype tags in a courtyard, on a laptop that has had no signal for three days, from
 * a page that was opened before the signal went. A hosted chart API is out for the obvious reason,
 * and an npm package is out for a less obvious one: `frontend/package.json` carries no QR library
 * today, and adding one on my own initiative puts a transitive dependency tree — and its future
 * CVEs and its future breaking major — under a feature whose entire specification is 300 lines of
 * ISO 18004 that will not change again. The spec was frozen in 2000 and the symbols printed today
 * must still scan in 2030; a stable standard implemented once is the cheaper thing to own.
 *
 * SO THIS IS DELIBERATELY NOT A GENERAL QR LIBRARY, and the limits are refusals rather than gaps:
 *
 *  - **Alphanumeric mode only.** The 45-character set (digits, capitals, space and eight
 *    punctuation marks) at 5.5 bits per character. `lib/workshopCodes.ts` emits nothing outside it
 *    — that is why the payload grammar is upper-case and colon-separated rather than free text.
 *    Byte mode would double the symbol for no gain and would invite arbitrary strings, including a
 *    person's name, into a code this file promises never to carry one of.
 *  - **Versions 1 to 6 only** (21×21 to 41×41). Version 7 upwards has to carry an extra 18-bit
 *    version block in two corners, and no reference this application generates comes close to
 *    version 6's 108 alphanumeric characters at level Q. {@link encodeQr} REFUSES a longer string
 *    rather than silently truncating it: a truncated identifier scans cleanly and resolves to the
 *    wrong record, which is the single failure this whole feature exists to prevent.
 *
 * VERIFIED AGAINST AN INDEPENDENT ENCODER, not against itself. `frontend/e2e/workshop-codes.spec.ts`
 * compares every module of every mask against matrices generated by reportlab's QR encoder — a
 * different implementation, in a different language, that already ships in `backend/.venv`. Mask
 * SELECTION is the one thing not compared, because reportlab's penalty scorer has two departures
 * from the standard (its vertical rule-3 pass compares a tuple against a list and so never fires,
 * and it looks only for the dark-first finder-lookalike). Both choices produce a legal, scannable
 * symbol; ours implements the rules as written.
 *
 * PURE, in the sense `lib/marketAnalysis.ts` is: no React, no fetch, no DOM. It returns a matrix of
 * booleans and, for convenience, an SVG path string. Both the on-screen preview and the printed
 * sheet render from the same matrix, so what a designer checks on the screen is what the printer
 * puts on the card.
 */

/** The 45 characters alphanumeric mode can carry, in the order that defines their values. */
const ALPHANUMERIC = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:";

/** Error correction levels, and the two bits each contributes to the format information block. */
export type QrEccLevel = "L" | "M" | "Q" | "H";

const ECC_FORMAT_BITS: Record<QrEccLevel, number> = { L: 0b01, M: 0b00, Q: 0b11, H: 0b10 };

/**
 * The smallest and largest symbols this file will build. See the header: the ceiling is a refusal,
 * not an omission, and {@link MAX_VERSION} may not be raised without adding the version
 * information block that versions 7 and up require in two corners.
 */
const MIN_VERSION = 1;
const MAX_VERSION = 6;

/** Total codewords (data + error correction) in versions 1–6. */
const TOTAL_CODEWORDS = [26, 44, 70, 100, 134, 172];

/**
 * Alignment pattern centre coordinates per version. Version 1 has none; 2–6 have a single extra
 * pattern whose centre is the second coordinate in each pair.
 */
const ALIGNMENT_CENTRES: number[][] = [[], [6, 18], [6, 22], [6, 26], [6, 30], [6, 34]];

/**
 * How a version's codewords are cut into Reed-Solomon blocks, per error correction level.
 *
 * `[ecPerBlock, group1Blocks, group1DataCodewords, group2Blocks, group2DataCodewords]`. Group 2
 * exists only where the standard splits a version into blocks of two different sizes (5-Q and 5-H
 * here); its data count is always exactly one more than group 1's.
 *
 * Written out rather than derived, because every row is checkable against ISO 18004 table 9 by
 * arithmetic: (g1Blocks × (g1Data + ec)) + (g2Blocks × (g2Data + ec)) must equal
 * {@link TOTAL_CODEWORDS} for that version. The spec test asserts exactly that for all 24 rows,
 * which is what turns a transcription slip into a red test instead of an unreadable card.
 */
const BLOCKS: Record<QrEccLevel, number[][]> = {
  //           ec  g1  g1data  g2  g2data
  L: [
    [7, 1, 19, 0, 0],
    [10, 1, 34, 0, 0],
    [15, 1, 55, 0, 0],
    [20, 1, 80, 0, 0],
    [26, 1, 108, 0, 0],
    [18, 2, 68, 0, 0]
  ],
  M: [
    [10, 1, 16, 0, 0],
    [16, 1, 28, 0, 0],
    [26, 1, 44, 0, 0],
    [18, 2, 32, 0, 0],
    [24, 2, 43, 0, 0],
    [16, 4, 27, 0, 0]
  ],
  Q: [
    [13, 1, 13, 0, 0],
    [22, 1, 22, 0, 0],
    [18, 2, 17, 0, 0],
    [26, 2, 24, 0, 0],
    [18, 2, 15, 2, 16],
    [24, 4, 19, 0, 0]
  ],
  H: [
    [17, 1, 9, 0, 0],
    [28, 1, 16, 0, 0],
    [22, 2, 13, 0, 0],
    [16, 4, 9, 0, 0],
    [22, 2, 11, 2, 12],
    [28, 4, 15, 0, 0]
  ]
};

/**
 * Bits of padding the standard adds after the last codeword, per version. Zero for version 1 and
 * seven for versions 2–6. They are written as light modules and carry nothing; omitting them leaves
 * seven modules of the symbol undefined, which some decoders read and some do not.
 */
const REMAINDER_BITS = [0, 7, 7, 7, 7, 7];

/* ────────────────────────────────────────────────────────────────────────────
 * GF(256) — the field Reed-Solomon works in
 *
 * Built once at module load from the primitive polynomial x⁸+x⁴+x³+x²+1 (0x11D), which is the one
 * QR specifies. Two 256-entry tables turn every field multiplication into two lookups and an add.
 * ──────────────────────────────────────────────────────────────────────────── */

const GF_EXP = new Uint8Array(512);
const GF_LOG = new Uint8Array(256);

(() => {
  let x = 1;
  for (let i = 0; i < 255; i++) {
    GF_EXP[i] = x;
    GF_LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  // The tail repeats the table so an exponent sum up to 508 needs no modulo in the hot loop.
  for (let i = 255; i < 512; i++) GF_EXP[i] = GF_EXP[i - 255];
})();

function gfMultiply(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return GF_EXP[GF_LOG[a] + GF_LOG[b]];
}

/** The generator polynomial whose roots are α⁰…α^(degree-1), as coefficients high-order first. */
function generatorPolynomial(degree: number): Uint8Array {
  let poly = new Uint8Array([1]);
  for (let i = 0; i < degree; i++) {
    const next = new Uint8Array(poly.length + 1);
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j];
      next[j + 1] ^= gfMultiply(poly[j], GF_EXP[i]);
    }
    poly = next;
  }
  return poly;
}

/** The `ecCount` error correction codewords for one block of data codewords. */
function errorCorrectionFor(data: Uint8Array, ecCount: number): Uint8Array {
  const generator = generatorPolynomial(ecCount);
  const remainder = new Uint8Array(ecCount);
  for (const byte of data) {
    const factor = byte ^ remainder[0];
    remainder.copyWithin(0, 1);
    remainder[ecCount - 1] = 0;
    if (factor !== 0) {
      // generator[0] is always 1, so the leading term is what was just shifted out.
      for (let i = 0; i < ecCount; i++) remainder[i] ^= gfMultiply(generator[i + 1], factor);
    }
  }
  return remainder;
}

/* ────────────────────────────────────────────────────────────────────────────
 * Bit assembly
 * ──────────────────────────────────────────────────────────────────────────── */

class BitBuffer {
  private bits: number[] = [];

  put(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i--) this.bits.push((value >>> i) & 1);
  }

  get length(): number {
    return this.bits.length;
  }

  /** Pad to a whole number of bytes and return them. */
  toBytes(): Uint8Array {
    const out = new Uint8Array(Math.ceil(this.bits.length / 8));
    this.bits.forEach((bit, index) => {
      if (bit) out[index >>> 3] |= 0x80 >>> (index & 7);
    });
    return out;
  }
}

/** Whether every character of `text` can be carried by alphanumeric mode. */
export function isQrAlphanumeric(text: string): boolean {
  for (const character of text) {
    if (!ALPHANUMERIC.includes(character)) return false;
  }
  return true;
}

/**
 * How many alphanumeric characters fit in one version at one level.
 *
 * Derived from the block table rather than tabulated separately, so a capacity and a block layout
 * cannot drift apart: two characters share 11 bits, a lone trailing one takes 6, and the header is
 * 4 mode bits plus a 9-bit character count (9 for versions 1–9, which is every version here).
 */
export function qrCapacity(version: number, level: QrEccLevel): number {
  const [, g1Blocks, g1Data, g2Blocks, g2Data] = BLOCKS[level][version - 1];
  const dataBits = (g1Blocks * g1Data + g2Blocks * g2Data) * 8 - 4 - 9;
  const pairs = Math.floor(dataBits / 11);
  // A leftover of 6 bits or more carries one more character; fewer carries none.
  return pairs * 2 + (dataBits - pairs * 11 >= 6 ? 1 : 0);
}

/** Why a string could not be turned into a symbol. Carries a sentence fit to show a designer. */
export class QrEncodeError extends Error {
  readonly reason: "NOT_ALPHANUMERIC" | "TOO_LONG" | "EMPTY";

  constructor(reason: "NOT_ALPHANUMERIC" | "TOO_LONG" | "EMPTY", message: string) {
    super(message);
    this.name = "QrEncodeError";
    this.reason = reason;
  }
}

/* ────────────────────────────────────────────────────────────────────────────
 * The symbol
 * ──────────────────────────────────────────────────────────────────────────── */

export type QrSymbol = {
  /** `matrix[row][column]` — true is a dark module. Row 0 is the top. */
  matrix: boolean[][];
  /** Modules per side: 17 + 4 × version. */
  size: number;
  version: number;
  level: QrEccLevel;
  /** Which of the eight masks was applied. Exposed so a test can pin it. */
  mask: number;
};

function newMatrix(size: number): boolean[][] {
  return Array.from({ length: size }, () => new Array<boolean>(size).fill(false));
}

/** Draw one 7×7 finder pattern with its light separator, anchored at the given top-left corner. */
function drawFinder(matrix: boolean[][], reserved: boolean[][], top: number, left: number): void {
  const size = matrix.length;
  for (let row = -1; row <= 7; row++) {
    for (let column = -1; column <= 7; column++) {
      const r = top + row;
      const c = left + column;
      if (r < 0 || r >= size || c < 0 || c >= size) continue;
      const ring = Math.max(Math.abs(row - 3), Math.abs(column - 3));
      matrix[r][c] = ring !== 2 && ring <= 3;
      reserved[r][c] = true;
    }
  }
}

/** Every module that carries a function pattern or a reserved block, drawn before any data. */
function drawFunctionPatterns(matrix: boolean[][], reserved: boolean[][], version: number): void {
  const size = matrix.length;

  drawFinder(matrix, reserved, 0, 0);
  drawFinder(matrix, reserved, 0, size - 7);
  drawFinder(matrix, reserved, size - 7, 0);

  // Timing patterns: alternating modules along row 6 and column 6, between the finders.
  for (let i = 8; i < size - 8; i++) {
    const dark = i % 2 === 0;
    matrix[6][i] = dark;
    reserved[6][i] = true;
    matrix[i][6] = dark;
    reserved[i][6] = true;
  }

  // Alignment patterns, at every combination of the version's centres except the three that would
  // land on a finder.
  const centres = ALIGNMENT_CENTRES[version - 1];
  for (const centreRow of centres) {
    for (const centreColumn of centres) {
      const onFinder =
        (centreRow === 6 && centreColumn === 6) ||
        (centreRow === 6 && centreColumn === size - 7) ||
        (centreRow === size - 7 && centreColumn === 6);
      if (onFinder) continue;
      for (let row = -2; row <= 2; row++) {
        for (let column = -2; column <= 2; column++) {
          matrix[centreRow + row][centreColumn + column] = Math.max(Math.abs(row), Math.abs(column)) !== 1;
          reserved[centreRow + row][centreColumn + column] = true;
        }
      }
    }
  }

  // The format information blocks are written after masking, but their modules must be reserved
  // now or the data placement would run straight through them.
  for (let i = 0; i <= 8; i++) {
    if (i !== 6) {
      reserved[8][i] = true;
      reserved[i][8] = true;
    }
  }
  for (let i = 0; i < 8; i++) {
    reserved[8][size - 1 - i] = true;
    reserved[size - 1 - i][8] = true;
  }
  // The one module that is always dark, immediately above the bottom-left finder's format strip.
  matrix[size - 8][8] = true;
  reserved[size - 8][8] = true;
}

/** The 15-bit BCH-protected format information for a level and mask. */
function formatBits(level: QrEccLevel, mask: number): number {
  const data = (ECC_FORMAT_BITS[level] << 3) | mask;
  let remainder = data;
  for (let i = 0; i < 10; i++) remainder = (remainder << 1) ^ ((remainder >>> 9) * 0x537);
  return (((data << 10) | remainder) ^ 0x5412) & 0x7fff;
}

function drawFormat(matrix: boolean[][], level: QrEccLevel, mask: number): void {
  const size = matrix.length;
  const bits = formatBits(level, mask);
  const bit = (index: number) => ((bits >>> index) & 1) === 1;

  // First copy: down the left of the top-left finder, then right along row 8.
  for (let i = 0; i <= 5; i++) matrix[i][8] = bit(i);
  matrix[7][8] = bit(6);
  matrix[8][8] = bit(7);
  matrix[8][7] = bit(8);
  for (let i = 9; i < 15; i++) matrix[8][14 - i] = bit(i);

  // Second copy: right along row 8 from the far edge, then up the bottom-left finder's column.
  for (let i = 0; i < 8; i++) matrix[8][size - 1 - i] = bit(i);
  for (let i = 8; i < 15; i++) matrix[size - 15 + i][8] = bit(i);
}

/** Whether mask `mask` inverts the module at (row, column). Straight from ISO 18004 table 10. */
function maskInverts(mask: number, row: number, column: number): boolean {
  switch (mask) {
    case 0:
      return (row + column) % 2 === 0;
    case 1:
      return row % 2 === 0;
    case 2:
      return column % 3 === 0;
    case 3:
      return (row + column) % 3 === 0;
    case 4:
      return (Math.floor(row / 2) + Math.floor(column / 3)) % 2 === 0;
    case 5:
      return ((row * column) % 2) + ((row * column) % 3) === 0;
    case 6:
      return (((row * column) % 2) + ((row * column) % 3)) % 2 === 0;
    default:
      return (((row + column) % 2) + ((row * column) % 3)) % 2 === 0;
  }
}

/**
 * The four penalty rules, as written in the standard, summed. Lower is better.
 *
 * The point of them is that a symbol should not contain large flat areas or anything that looks
 * like a finder pattern, because both make a scanner work harder — and the scanner here is a
 * handset camera held over a printed card in a courtyard, which is the least forgiving reading
 * condition this application has.
 */
function penalty(matrix: boolean[][]): number {
  const size = matrix.length;
  let score = 0;

  // Rule 1 — runs of five or more identical modules, in both directions.
  for (let outer = 0; outer < size; outer++) {
    for (const horizontal of [true, false]) {
      let runValue = horizontal ? matrix[outer][0] : matrix[0][outer];
      let runLength = 1;
      for (let inner = 1; inner < size; inner++) {
        const value = horizontal ? matrix[outer][inner] : matrix[inner][outer];
        if (value === runValue) {
          runLength++;
          continue;
        }
        if (runLength >= 5) score += runLength - 2;
        runValue = value;
        runLength = 1;
      }
      if (runLength >= 5) score += runLength - 2;
    }
  }

  // Rule 2 — every 2×2 block of one colour.
  for (let row = 0; row < size - 1; row++) {
    for (let column = 0; column < size - 1; column++) {
      const value = matrix[row][column];
      if (value === matrix[row][column + 1] && value === matrix[row + 1][column] && value === matrix[row + 1][column + 1]) {
        score += 3;
      }
    }
  }

  // Rule 3 — anything a scanner could mistake for a finder pattern: 1011101 with four light
  // modules on either side. BOTH orientations count, in both directions.
  const forward = [true, false, true, true, true, false, true, false, false, false, false];
  const backward = [...forward].reverse();
  for (let outer = 0; outer < size; outer++) {
    for (const horizontal of [true, false]) {
      for (let start = 0; start + 11 <= size; start++) {
        let matchesForward = true;
        let matchesBackward = true;
        for (let offset = 0; offset < 11; offset++) {
          const value = horizontal ? matrix[outer][start + offset] : matrix[start + offset][outer];
          if (value !== forward[offset]) matchesForward = false;
          if (value !== backward[offset]) matchesBackward = false;
        }
        if (matchesForward) score += 40;
        if (matchesBackward) score += 40;
      }
    }
  }

  // Rule 4 — how far the proportion of dark modules strays from half.
  let dark = 0;
  for (const row of matrix) for (const value of row) if (value) dark++;
  const percent = (dark * 100) / (size * size);
  score += Math.floor(Math.abs(percent - 50) / 5) * 10;

  return score;
}

/**
 * Turn `text` into the interleaved codeword stream the symbol carries.
 *
 * The interleaving is the part worth understanding: the blocks are woven together codeword by
 * codeword so that a smudge covering a contiguous patch of the printed symbol damages a little of
 * every block rather than destroying one of them outright. On a card that lives in a workshop, that
 * is the difference between a scan that still resolves and one that does not.
 */
function buildCodewords(text: string, version: number, level: QrEccLevel): Uint8Array {
  const [ecPerBlock, g1Blocks, g1Data, g2Blocks, g2Data] = BLOCKS[level][version - 1];
  const totalData = g1Blocks * g1Data + g2Blocks * g2Data;

  const buffer = new BitBuffer();
  buffer.put(0b0010, 4); // alphanumeric mode indicator
  buffer.put(text.length, 9); // character count, 9 bits for versions 1–9
  for (let i = 0; i + 1 < text.length; i += 2) {
    buffer.put(ALPHANUMERIC.indexOf(text[i]) * 45 + ALPHANUMERIC.indexOf(text[i + 1]), 11);
  }
  if (text.length % 2 === 1) buffer.put(ALPHANUMERIC.indexOf(text[text.length - 1]), 6);

  // Terminator: up to four zero bits, fewer when the capacity is nearly full.
  buffer.put(0, Math.min(4, totalData * 8 - buffer.length));
  // Pad to a byte boundary, then alternate 0xEC / 0x11 to the end. The two pad bytes are specified
  // values, not arbitrary filler — a decoder uses them to tell padding from data.
  if (buffer.length % 8 !== 0) buffer.put(0, 8 - (buffer.length % 8));
  const bytes = buffer.toBytes();
  const data = new Uint8Array(totalData);
  data.set(bytes.subarray(0, Math.min(bytes.length, totalData)));
  for (let i = bytes.length; i < totalData; i++) data[i] = (i - bytes.length) % 2 === 0 ? 0xec : 0x11;

  const dataBlocks: Uint8Array[] = [];
  const ecBlocks: Uint8Array[] = [];
  let offset = 0;
  for (let block = 0; block < g1Blocks + g2Blocks; block++) {
    const length = block < g1Blocks ? g1Data : g2Data;
    const slice = data.subarray(offset, offset + length);
    offset += length;
    dataBlocks.push(slice);
    ecBlocks.push(errorCorrectionFor(slice, ecPerBlock));
  }

  const out = new Uint8Array(TOTAL_CODEWORDS[version - 1]);
  let written = 0;
  const longestData = Math.max(g1Data, g2Data);
  for (let index = 0; index < longestData; index++) {
    for (const block of dataBlocks) if (index < block.length) out[written++] = block[index];
  }
  for (let index = 0; index < ecPerBlock; index++) {
    for (const block of ecBlocks) out[written++] = block[index];
  }
  return out;
}

/** Lay the codeword stream into the matrix in the standard two-column upward/downward zigzag. */
function drawCodewords(matrix: boolean[][], reserved: boolean[][], codewords: Uint8Array, version: number): void {
  const size = matrix.length;
  const totalBits = codewords.length * 8 + REMAINDER_BITS[version - 1];
  let bitIndex = 0;

  for (let right = size - 1; right >= 1; right -= 2) {
    // Column 6 is the vertical timing pattern; the pairs step over it entirely.
    const rightColumn = right <= 6 ? right - 1 : right;
    for (let vertical = 0; vertical < size; vertical++) {
      for (let offset = 0; offset < 2; offset++) {
        const column = rightColumn - offset;
        const upward = ((rightColumn + 1) & 2) === 0;
        const row = upward ? size - 1 - vertical : vertical;
        if (reserved[row][column]) continue;
        if (bitIndex >= totalBits) continue;
        // Remainder bits past the last codeword stay light; they carry nothing.
        const byte = bitIndex >>> 3;
        matrix[row][column] = byte < codewords.length && ((codewords[byte] >>> (7 - (bitIndex & 7))) & 1) === 1;
        bitIndex++;
      }
    }
  }
}

/**
 * Build the symbol for `text` at one version, level and mask.
 *
 * Exported for the spec, which drives all eight masks against reference matrices from a second
 * implementation. Application code wants {@link encodeQr}, which picks both for itself.
 */
export function buildQrMatrix(text: string, version: number, level: QrEccLevel, mask: number): boolean[][] {
  const size = 17 + 4 * version;
  const matrix = newMatrix(size);
  const reserved = newMatrix(size);
  drawFunctionPatterns(matrix, reserved, version);
  drawCodewords(matrix, reserved, buildCodewords(text, version, level), version);
  for (let row = 0; row < size; row++) {
    for (let column = 0; column < size; column++) {
      if (!reserved[row][column] && maskInverts(mask, row, column)) matrix[row][column] = !matrix[row][column];
    }
  }
  drawFormat(matrix, level, mask);
  return matrix;
}

/**
 * Encode `text` as the smallest symbol that will hold it at `level`, with the mask the standard's
 * penalty rules prefer.
 *
 * Throws {@link QrEncodeError} rather than returning a degraded symbol. A caller printing forty
 * cards wants to know which one it could not draw; a caller that silently got a shorter string
 * back would print a tag that scans to a record that does not exist.
 */
export function encodeQr(text: string, level: QrEccLevel = "Q"): QrSymbol {
  if (!text) throw new QrEncodeError("EMPTY", "There is nothing to encode.");
  if (!isQrAlphanumeric(text)) {
    throw new QrEncodeError(
      "NOT_ALPHANUMERIC",
      "This code contains characters a compact QR symbol cannot carry. Codes are upper-case letters, digits and the punctuation the standard allows."
    );
  }

  let version = 0;
  for (let candidate = MIN_VERSION; candidate <= MAX_VERSION; candidate++) {
    if (text.length <= qrCapacity(candidate, level)) {
      version = candidate;
      break;
    }
  }
  if (!version) {
    throw new QrEncodeError(
      "TOO_LONG",
      `This code is ${text.length} characters, and the largest symbol this app draws holds ${qrCapacity(MAX_VERSION, level)}.`
    );
  }

  let best: boolean[][] | null = null;
  let bestMask = 0;
  let bestScore = Number.POSITIVE_INFINITY;
  for (let mask = 0; mask < 8; mask++) {
    const candidate = buildQrMatrix(text, version, level, mask);
    const score = penalty(candidate);
    if (score < bestScore) {
      bestScore = score;
      best = candidate;
      bestMask = mask;
    }
  }

  return { matrix: best as boolean[][], size: 17 + 4 * version, version, level, mask: bestMask };
}

/**
 * The dark modules of a symbol as one SVG path, in a coordinate space of 1 unit per module.
 *
 * ONE PATH, NOT ONE RECT PER MODULE. A version 4 symbol is 1089 modules; as `<rect>`s that is a
 * thousand DOM nodes per card and a print sheet of thirty cards that a field laptop takes seconds
 * to lay out. It also renders more reliably: adjacent rects leave hairline seams at some zoom
 * levels in some browsers, and a seam across a QR module is exactly the artefact that makes a
 * scanner hesitate.
 *
 * The `quiet` zone is included in the returned {@link QrSvg.extent} rather than left to the caller,
 * because a symbol printed hard against a card's border does not scan and there is no way to see
 * that on screen. Four modules is the standard's minimum.
 */
export type QrSvg = {
  path: string;
  /** Side length of the drawing including the quiet zone, in module units — use as the viewBox. */
  extent: number;
  symbol: QrSymbol;
};

export function qrSvgPath(symbol: QrSymbol, quiet = 4): QrSvg {
  const parts: string[] = [];
  for (let row = 0; row < symbol.size; row++) {
    let column = 0;
    while (column < symbol.size) {
      if (!symbol.matrix[row][column]) {
        column++;
        continue;
      }
      // Runs are merged horizontally: a row of eight dark modules becomes one 8×1 rectangle rather
      // than eight 1×1 ones, which roughly halves the path on a typical symbol.
      let run = 1;
      while (column + run < symbol.size && symbol.matrix[row][column + run]) run++;
      parts.push(`M${column + quiet} ${row + quiet}h${run}v1h-${run}z`);
      column += run;
    }
  }
  return { path: parts.join(""), extent: symbol.size + quiet * 2, symbol };
}
